Repository kubesphere/ks-devops, pull requests merged in 2021-09, with the labels that each got.

#212 Set crumb into header for Jenkins proxy request
  pkg/api/devops/v1alpha4/zz_generated.deepcopy.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/authentication/token/jwt_test.go
  pkg/apiserver/runtime/runtime_test.go
  pkg/client/devops/jenkins/pure_request.go
  pkg/client/devops/jenkins/request.go
  pkg/kapis/devops/v1alpha2/proxy.go
  pkg/kapis/devops/v1alpha2/proxy_test.go
  pkg/kapis/devops/v1alpha2/register.go
Labels: kind/feature, size/L, approved, lgtm

#210 Support trigger a parameterized Pipeline in PipelineRun reconciler
  config/samples/devops_v1alpha4_pipelinerun_with_parameters.yaml
  controllers/jenkins/pipelinerun/pipelinerun_controller.go
  controllers/jenkins/pipelinerun/utils.go
  controllers/jenkins/pipelinerun/utils_test.go
  go.mod
  go.sum
Labels: kind/feature, size/L, lgtm

#214 Support multi-branch pipeline build and fetching build
  config/samples/devops_v1alpha4_pipelinerun_multi_branch_demo.yaml
  controllers/jenkins/pipelinerun/pipelinerun_controller.go
  controllers/jenkins/pipelinerun/pipelinerun_controller_test.go
  go.mod
  go.sum
  pkg/api/devops/v1alpha4/pipelinerun_types.go
  pkg/api/devops/v1alpha4/pipelinerun_types_test.go
Labels: kind/feature, size/L, lgtm

#218 Add a new GitHub action to create nightly build
  .github/workflows/nightly-build.yaml
Labels: size/L, approved, lgtm

#221 Fix the unit tests of controllers
  controllers/devopscredential/devopscredential_controller_test.go
  controllers/devopsproject/devopsproject_controller.go
  controllers/devopsproject/devopsproject_controller_test.go
  controllers/pipeline/pipeline_controller_test.go
  controllers/s2ibinary/s2ibinary_controller_test.go
  controllers/s2irun/s2irun_controller_test.go
  go.mod
  go.sum
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/informers/externalversions/generic.go
  pkg/kapis/devops/v1alpha2/register.go
  pkg/kapis/devops/v1alpha3/register.go
  pkg/models/resources/v1alpha3/devops/devops.go
Labels: approved, size/XXL, kind/cleanup

#219 Add event recorder into PipelineRun reconciler
  controllers/jenkins/pipelinerun/pipelinerun_controller.go
  pkg/api/devops/v1alpha4/pipelinerun_types.go
Labels: kind/feature, approved, lgtm, size/S

#223 fix ks official repo url
  README.md
Labels: approved, lgtm, size/XS

#213 Provide more guide document for the potential contributors
  CONTRIBUTING.md
  README.md
  docs/README.md
  docs/cli.md
  docs/installation.md
  docs/projects.md
Labels: documentation, size/L, approved

#226 Add config file for codecov
  codecov.yml
Labels: approved, lgtm, size/S, kind/cleanup

#222 Retrieve PipelineRun stages status and store it into annotations
  controllers/jenkins/pipelinerun/pipelinerun_controller.go
  go.mod
  go.sum
  pkg/api/devops/v1alpha4/groupversion_info.go
Labels: kind/feature, approved, lgtm, size/M

#208 Fix: delete PipelineRun resources along with the deletion of Pipeline
  .github/workflows/integration-test.yaml
  .gitignore
  Makefile
  cmd/controller/app/controllers.go
  controllers/suite_test.go
  controllers/tekton/pipeline/pipeline_controller_test.go
  controllers/tekton/pipeline_controller.go
  controllers/tekton/pipeline_controller_test.go
  controllers/tekton/pipelinerun_controller.go
  controllers/tekton/pipelinerun_controller_test.go
  controllers/tekton/suite_test.go
  controllers/tekton/testdata/README.md
  controllers/tekton/utils.go
  controllers/tekton/utils_test.go
  hack/download_tekton_testdata.sh
Labels: lgtm, size/XL

#231 Backup git repo to gitee.com
  .github/workflows/backup.yaml
Labels: approved, size/S, kind/cleanup

#230 Add PipelineRuns list API
  Makefile
  cmd/apiserver/app/options/options.go
  config/samples/devops_v1alpha4_pipelinerun_multi_branch_demo.yaml
  controllers/jenkins/pipelinerun/pipelinerun_controller.go
  controllers/jenkins/pipelinerun/pipelinerun_controller_test.go
  controllers/s2ibinary/s2ibinary_controller_test.go
  controllers/s2irun/s2irun_controller_test.go
  go.mod
  go.sum
  pkg/api/devops/v1alpha1/register.go
  pkg/api/devops/v1alpha4/groupversion_info.go
  pkg/api/types.go
  pkg/api/utils.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/query/types.go
  pkg/apiserver/query/types_test.go
  pkg/client/clientset/versioned/typed/devops/v1alpha1/devops_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/kapis/devops/v1alpha4/backwardlisthandler.go
  pkg/kapis/devops/v1alpha4/backwardlisthandler_test.go
  pkg/kapis/devops/v1alpha4/handler.go
  pkg/kapis/devops/v1alpha4/register.go
  pkg/kapis/devops/v1alpha4/util.go
  pkg/kapis/devops/v1alpha4/util_test.go
  pkg/models/devops/devops.go
  pkg/models/resources/v1alpha3/devops/devops.go
  pkg/models/resources/v1alpha3/interface.go
  pkg/models/resources/v1alpha3/interface_test.go
  pkg/models/resources/v1alpha3/listhandler.go
Labels: kind/feature, lgtm, do-not-merge/hold, size/XXL

#233 Provide PipelineRuns creation API
  .gitignore
  pkg/client/devops/pipeline.go
  pkg/kapis/devops/v1alpha4/handler.go
  pkg/kapis/devops/v1alpha4/register.go
  pkg/kapis/devops/v1alpha4/util.go
  pkg/kapis/devops/v1alpha4/util_test.go
Labels: kind/feature, size/L, lgtm

#236 Bump version of jenkins-zh/jenkins-client
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#235 Provide getting PipelineRun API
  pkg/kapis/devops/v1alpha4/handler.go
  pkg/kapis/devops/v1alpha4/register.go
Labels: lgtm, size/S

#238 Move PipelineRun CRD version to v1alpha3
  Makefile
  PROJECT
  cmd/apiserver/app/options/options.go
  cmd/controller/app/server.go
  config/crd/bases/devops.kubesphere.io_pipelineruns.yaml
  config/samples/devops_v1alpha4_pipelinerun.yaml
  config/samples/devops_v1alpha4_pipelinerun_multi_branch_demo.yaml
  config/samples/devops_v1alpha4_pipelinerun_with_parameters.yaml
  controllers/jenkins/pipelinerun/pipelinerun_controller.go
  controllers/jenkins/pipelinerun/pipelinerun_controller_test.go
  controllers/jenkins/pipelinerun/utils.go
  controllers/jenkins/pipelinerun/utils_test.go
  controllers/suite_test.go
  pkg/api/devops/pipelinerun/v1alpha3/groupversion_info.go
  pkg/api/devops/pipelinerun/v1alpha3/pipelinerun_types.go
  pkg/api/devops/pipelinerun/v1alpha3/pipelinerun_types_test.go
  pkg/api/devops/pipelinerun/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/addtoscheme_devops_v1alpha3.go
  pkg/apis/apis.go
  pkg/apiserver/apiserver.go
  pkg/kapis/devops/v1alpha3/pipelinerun/backwardlisthandler.go
  pkg/kapis/devops/v1alpha3/pipelinerun/backwardlisthandler_test.go
  pkg/kapis/devops/v1alpha3/pipelinerun/handler.go
  pkg/kapis/devops/v1alpha3/pipelinerun/register.go
  pkg/kapis/devops/v1alpha3/pipelinerun/util.go
  pkg/kapis/devops/v1alpha3/pipelinerun/util_test.go
  pkg/kapis/devops/v1alpha3/register.go
Labels: lgtm, size/XL

#239 Add action field into PipelineRunSpec
  config/crd/bases/devops.kubesphere.io_pipelineruns.yaml
  pkg/api/devops/pipelinerun/v1alpha3/pipelinerun_types.go
Labels: approved, lgtm, size/S

#237 Put the command line ks into the tools image
  config/dockerfiles/tools/Dockerfile
Labels: approved, lgtm, size/XS

#242 Filter nil items in result list
  pkg/kapis/devops/v1alpha2/devops.go
  pkg/models/resources/v1alpha3/interface.go
  pkg/models/resources/v1alpha3/interface_test.go
Labels: lgtm, size/M, kind/bug

#245 Bump go version from 1.13 to 1.16
  .github/workflows/build.yaml
  .github/workflows/lint.yaml
  CONTRIBUTING.md
  config/dockerfiles/apiserver/Dockerfile
  config/dockerfiles/controller-manager/Dockerfile
  config/dockerfiles/tools/Dockerfile
  go.mod
  go.sum
Labels: lgtm, size/S, kind/chore

#243 Add support delete job history records once pipelinerun was deleted
  controllers/jenkins/pipelinerun/pipelinerun_controller.go
  controllers/jenkins/pipelinerun/pipelinerun_controller_test.go
  controllers/jenkins/pipelinerun/setup_test.go
  pkg/api/devops/pipelinerun/v1alpha3/pipelinerun_types.go
Labels: kind/feature, size/L, approved, lgtm

#244 Provide Pipeline Synchronizer to synchronize PipelineRun from Jenkins
  cmd/controller/app/controllers.go
  controllers/devopsproject/devopsproject_controller.go
  controllers/jenkins/pipelinerun/pipelinerun_controller.go
  controllers/jenkins/pipelinerun/pipelinerun_synchronizer.go
  controllers/jenkins/pipelinerun/pipelinerun_synchronizer_test.go
  controllers/jenkins/pipelinerun/utils.go
  controllers/jenkins/pipelinerun/utils_test.go
  controllers/pipeline/pipeline_controller.go
  go.mod
  go.sum
  pkg/api/devops/v1alpha3/pipeline_types.go
  pkg/kapis/devops/v1alpha3/pipelinerun/handler.go
  pkg/kapis/devops/v1alpha3/pipelinerun/util.go
Labels: kind/feature, lgtm, size/XL

#247 Add additional columns for Pipeline and PipelineRun
  Makefile
  config/crd/bases/devops.kubesphere.io_devopsprojects.yaml
  config/crd/bases/devops.kubesphere.io_fakes.yaml
  config/crd/bases/devops.kubesphere.io_pipelineruns.yaml
  config/crd/bases/devops.kubesphere.io_pipelines.yaml
  config/crd/bases/devops.kubesphere.io_s2ibinaries.yaml
  config/crd/bases/devops.kubesphere.io_s2ibuilders.yaml
  config/crd/bases/devops.kubesphere.io_s2ibuildertemplates.yaml
  config/crd/bases/devops.kubesphere.io_s2iruns.yaml
  pkg/api/devops/pipelinerun/v1alpha3/pipelinerun_types.go
  pkg/api/devops/v1alpha3/pipeline_types.go
Labels: kind/feature, approved, lgtm, size/M

#246 Relocate v1alpha3.PipelineRun type
  controllers/jenkins/pipelinerun/pipelinerun_controller.go
  controllers/jenkins/pipelinerun/pipelinerun_controller_test.go
  controllers/jenkins/pipelinerun/pipelinerun_synchronizer.go
  controllers/jenkins/pipelinerun/pipelinerun_synchronizer_test.go
  controllers/jenkins/pipelinerun/utils.go
  controllers/jenkins/pipelinerun/utils_test.go
  controllers/suite_test.go
  go.mod
  go.sum
  main.go
  pkg/api/devops/pipelinerun/v1alpha3/groupversion_info.go
  pkg/api/devops/pipelinerun/v1alpha3/zz_generated.deepcopy.go
  pkg/api/devops/v1alpha1/openapi_generated.go
  pkg/api/devops/v1alpha1/zz_generated.deepcopy.go
  pkg/api/devops/v1alpha3/fake_types.go
  pkg/api/devops/v1alpha3/groupversion_info.go
  pkg/api/devops/v1alpha3/pipeline_types.go
  pkg/api/devops/v1alpha3/pipelinerun_types.go
  pkg/api/devops/v1alpha3/pipelinerun_types_test.go
  pkg/api/devops/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/apis.go
  pkg/client/devops/jenkins/pipeline_internal.go
  pkg/client/devops/jenkins/pipeline_internal_test.go
  pkg/kapis/devops/v1alpha3/pipelinerun/backwardlisthandler.go
  pkg/kapis/devops/v1alpha3/pipelinerun/backwardlisthandler_test.go
  pkg/kapis/devops/v1alpha3/pipelinerun/handler.go
  pkg/kapis/devops/v1alpha3/pipelinerun/register.go
  pkg/kapis/devops/v1alpha3/pipelinerun/util.go
  pkg/kapis/devops/v1alpha3/pipelinerun/util_test.go
Labels: lgtm, size/XL

#259 Support print the age of pipeline and pipelinerun
  config/crd/bases/devops.kubesphere.io_pipelineruns.yaml
  config/crd/bases/devops.kubesphere.io_pipelines.yaml
  pkg/api/devops/v1alpha3/pipeline_types.go
  pkg/api/devops/v1alpha3/pipelinerun_types.go
Labels: approved, lgtm, size/S, kind/chore

#264 Synchronize PipelineRun for multi branch pipeline
  controllers/jenkins/pipelinerun/pipelinerun_finder.go
  controllers/jenkins/pipelinerun/pipelinerun_finder_test.go
  controllers/jenkins/pipelinerun/pipelinerun_synchronizer.go
  controllers/jenkins/pipelinerun/pipelinerun_synchronizer_test.go
  pkg/kapis/devops/v1alpha3/pipelinerun/util.go
Labels: size/L

#276 Add shortNames,category for pipeline and pipelinerun
  config/crd/bases/devops.kubesphere.io_pipelineruns.yaml
  config/crd/bases/devops.kubesphere.io_pipelines.yaml
  pkg/api/devops/v1alpha3/pipeline_types.go
  pkg/api/devops/v1alpha3/pipelinerun_types.go
Labels: kind/feature, approved, lgtm, size/S

#277 Avoid interactive during the gh repo fork
  .gitpod.yml
Labels: approved, lgtm, size/XS, kind/chore

#251 Check existing PipelineRun with same run ID
  controllers/jenkins/pipelinerun/pipelinerun_controller.go
  controllers/jenkins/pipelinerun/pipelinerun_controller_test.go
Labels: size/L, lgtm, kind/bug

#224 Add Jenkins client in controller
  cmd/controller/app/server.go
  controllers/pipeline/pipeline_controller.go
  controllers/pipeline/pipeline_controller_test.go
  pkg/client/devops/fake/fakeJenkinsClient.go
  pkg/client/devops/fake/fakedevops.go
  pkg/client/devops/jclient/build.go
  pkg/client/devops/jclient/configuration.go
  pkg/client/devops/jclient/credential.go
  pkg/client/devops/jclient/jenkins.go
  pkg/client/devops/jclient/pipeline.go
  pkg/client/devops/jclient/project.go
  pkg/client/devops/jclient/projectPipeline.go
  pkg/client/devops/jclient/role.go
  pkg/client/devops/jenkins/jenkins.go
  pkg/client/devops/jenkins/pipeline.go
  pkg/client/devops/pipeline.go
  pkg/kapis/devops/v1alpha2/devops.go
  pkg/kapis/devops/v1alpha2/register.go
  pkg/models/devops/devops.go
Labels: size/L, lgtm, do-not-merge/hold

#280 Fix the wrong using of paging parameter start
  pkg/apiserver/query/types.go
  pkg/apiserver/query/types_test.go
  pkg/kapis/devops/v1alpha2/devops.go
  pkg/kapis/devops/v1alpha2/devops_test.go
Labels: bug, size/L, approved, lgtm, do-not-merge/hold

#285 Enable exported rule of revive for golangci-lint
  .golangci.yml
  controllers/jenkins/pipelinerun/pipelinerun_controller.go
  controllers/jenkins/pipelinerun/pipelinerun_controller_test.go
  controllers/jenkins/pipelinerun/pipelinerun_finder.go
  controllers/jenkins/pipelinerun/pipelinerun_finder_test.go
  controllers/jenkins/pipelinerun/pipelinerun_synchronizer.go
  controllers/jenkins/pipelinerun/pipelinerun_synchronizer_test.go
  controllers/jenkins/pipelinerun/utils.go
  pkg/api/devops/v1alpha3/groupversion_info.go
  pkg/api/devops/v1alpha3/pipelinerun_types.go
  pkg/client/devops/jenkins/configuration.go
  pkg/kapis/devops/v1alpha3/pipelinerun/backwardlisthandler.go
  pkg/kapis/devops/v1alpha3/pipelinerun/backwardlisthandler_test.go
  pkg/utils/reflectutils/deep.go
Labels: size/L, approved, lgtm, kind/cleanup

#282 Provide Pipeline metadata controller to update metadata from Jenkins
  cmd/controller/app/controllers.go
  controllers/jenkins/pipeline/metadata_converter.go
  controllers/jenkins/pipeline/pipeline_metadata_controller.go
  go.mod
  go.sum
  pkg/api/devops/v1alpha3/pipeline_types.go
Labels: kind/feature, size/L, lgtm

#288 Bump ks which in the tool image to v0.0.52
  config/dockerfiles/tools/Dockerfile
Labels: approved, lgtm, size/XS, kind/chore
