Repository kubesphere/ks-devops, pull requests merged in 2021-08, with the labels that each got.

#89 Add prometheus service monitor and rule
  charts/ks-devops/charts/jenkins/README.md
  charts/ks-devops/charts/jenkins/templates/prometheus-prometheusrule.yaml
  charts/ks-devops/charts/jenkins/templates/prometheus-servicemonitor.yaml
  charts/ks-devops/charts/jenkins/values.yaml
  charts/ks-devops/charts/s2i/README.md
  charts/ks-devops/charts/s2i/templates/prometheus-servicemonitor.yaml
  charts/ks-devops/charts/s2i/values.yaml
Labels: approved, lgtm, size/L

#98 Change the docker hub org from kubespheresig to kubespheredev
  .github/workflows/build.yaml
  README.md
  charts/ks-devops/values.yaml
Labels: approved, lgtm, size/S

#93 Fix ks-devops-apiserver crash while viewing parallel pipeline activity detail
  pkg/models/devops/devops.go
Labels: approved, kind/bug, lgtm, size/XS

#100 add tekton chart for installation
  README.md
  charts/ks-devops/Chart.yaml
  charts/ks-devops/README.md
  charts/ks-devops/charts/tekton-pipeline-0.25.0.tgz
  charts/ks-devops/values.yaml
Labels: ospp-2021, size/XXL

#111 Correct the GitHub org in the README file
  README.md
Labels: approved, size/S

#112 Add support to login ghcr.io in gitpod
  .gitpod.yml
Labels: approved, size/XS

#114 Correct github.repository_owner comparison condition due to org transfer
  .github/workflows/build.yaml
Labels: approved, lgtm, size/S, kind/bug

#99 Add license file which is the apache 2.0
  LICENSE
Labels: approved, lgtm

#115 Add a root API path which without the group name
  go.mod
  pkg/apiserver/runtime/runtime.go
  pkg/apiserver/runtime/runtime_test.go
  pkg/kapis/devops/v1alpha2/register.go
  pkg/kapis/devops/v1alpha3/handler.go
  pkg/kapis/devops/v1alpha3/register.go
  pkg/models/devops/devops.go
Labels: size/L, approved

#124 Align go version with version defined in go.mod
  .github/workflows/build.yaml
Labels: approved, lgtm, size/XS

#122 Fix the go module errors due to version conflicts of k8s
  .github/workflows/build.yaml
  go.mod
  go.sum
Labels: size/L, lgtm

#123 Fix the API of credential creating/updating failed due to URI is too long
  pkg/client/devops/jenkins/credential.go
Labels: lgtm, size/S

#181 Make the branch tekton-support can run GitHub actions
  .github/workflows/build.yaml
Labels: approved, size/XS

#175 Initialize PipelineRun type and controller
  PROJECT
  cmd/controller/app/controllers.go
  config/crd/bases/devops.kubesphere.io_pipelineruns.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_pipelineruns.yaml
  config/crd/patches/webhook_in_pipelineruns.yaml
  config/rbac/pipelinerun_editor_role.yaml
  config/rbac/pipelinerun_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/devops_v1alpha4_pipelinerun.yaml
  controllers/jenkins/pipelinerun/pipelinerun_controller.go
  controllers/suite_test.go
  pkg/api/devops/v1alpha4/groupversion_info.go
  pkg/api/devops/v1alpha4/pipelinerun_types.go
  pkg/api/devops/v1alpha4/zz_generated.deepcopy.go
Labels: lgtm, size/XL

#180 Add devcontainer config file
  .devcontainer/devcontainer.json
Labels: size/S

#182 Add more feature branches
  .github/workflows/build.yaml
Labels: approved, size/XS

#184 Skip golangci-lint cache due to flaky behaviors
  .github/workflows/build.yaml
  .github/workflows/lint.yaml
  .golangci.yml
Labels: approved, lgtm, size/M

#186 Add the desgin document of Jenkins config controller
  controllers/jenkinsconfig/README.md
Labels: approved, size/M

#190 Set crumb into request header to Jenkins automatically
  pkg/client/devops/jenkins/pure_request.go
  pkg/client/devops/jenkins/request.go
Labels: lgtm, size/S

#172 Add a collection of DevOps related projects
  README.md
  docs/projects.md
Labels: approved, size/S

#195 Fix the controller panic due to Jenkins job parse error
  pkg/client/devops/jenkins/pipeline_internal.go
Labels: approved, size/XS

#194 Improve the error message with getting Pipeline
  pkg/client/devops/jenkins/pipeline.go
  pkg/models/devops/devops.go
Labels: approved, size/XS

#193 fix(cmd/controller cmd/apiserver): remove term which depends on docker library
  cmd/apiserver/app/server.go
  cmd/controller/app/server.go
  go.mod
  go.sum
  pkg/utils/term/term.go
Labels: approved, size/M

#196 Support to install minikube in CodeSpaces automatically
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/init.sh
  .gitpod.Dockerfile
Labels: approved, size/M

#199 Add some badges into readme file
  README.md
Labels: approved, size/S

#176 Fix incorrect variable references and reset important default values
  Makefile
  charts/ks-devops/Chart.yaml
  charts/ks-devops/charts/jenkins/templates/jenkins-casc-config.yml
  charts/ks-devops/charts/jenkins/values.yaml
  charts/ks-devops/templates/NOTES.txt
  charts/ks-devops/templates/_helpers.tpl
  charts/ks-devops/templates/deployment-apiserver.yaml
  charts/ks-devops/templates/deployment-controller.yaml
  charts/ks-devops/templates/hpa.yaml
  charts/ks-devops/templates/ingress.yaml
  charts/ks-devops/templates/service-apiserver.yaml
  charts/ks-devops/templates/serviceaccount.yaml
  charts/ks-devops/templates/tests/test-connection.yaml
  charts/ks-devops/values.yaml
Labels: size/L, lgtm

#171 Add podman support in the Jenkins chart
  charts/ks-devops/README.md
  charts/ks-devops/charts/jenkins/README.md
  charts/ks-devops/charts/jenkins/templates/_helpers.tpl
  charts/ks-devops/charts/jenkins/templates/jenkins-casc-config.yml
  charts/ks-devops/charts/jenkins/values.yaml
Labels: approved, size/M

#200 feat(controllers/tekton): add finalizers to controllers of Pipeline and PipelineRun in version v2alpha1
  cmd/controller/app/controllers.go
  controllers/tekton/pipeline/pipeline_controller.go
  controllers/tekton/pipelinerun/pipelinerun_controller.go
  pkg/api/devops/v2alpha1/pipeline_types.go
  pkg/api/devops/v2alpha1/pipelinerun_types.go
Labels: size/L, lgtm

#201 Add documentation for Tekton support
  docs/tekton-support.md
Labels: size/L, lgtm

#110 Refactor: use JSON-based payload to create Jenkins pipeline
  controllers/pipeline/pipeline_controller.go
  go.mod
  go.sum
  pkg/client/devops/jclient/jenkins.go
  pkg/client/devops/jclient/projectPipeline.go
Labels: ospp-2021, size/L, lgtm

#76 Refine DevOps installation guide
  README.md
Labels: documentation, lgtm, size/M
