Repository kubesphere/ks-devops, pull requests merged in 2021-12, with the labels that each got.

#389 Bump up version of kubephere-sigs/ks to v0.0.60
  config/dockerfiles/tools/Dockerfile
Labels: approved, lgtm, size/XS, kind/chore, no-changelog

#394 Fix messy sequence of PipelineRuns
  controllers/jenkins/pipelinerun/utils.go
  pkg/kapis/devops/v1alpha3/pipelinerun/handler.go
  pkg/kapis/devops/v1alpha3/pipelinerun/listhandler.go
  pkg/kapis/devops/v1alpha3/pipelinerun/listhandler_test.go
Labels: size/L, approved, lgtm, kind/bug, tide/merge-method-squash

#398 Fix the problem caused by strange branch names that contain special characters
  cmd/controller/app/server.go
  controllers/jenkins/pipeline/metadata_converter.go
  controllers/jenkins/pipelinerun/pipelinerun_controller.go
  controllers/jenkins/pipelinerun/pipelinerun_controller_test.go
  controllers/jenkins/pipelinerun/pipelinerun_synchronizer_test.go
  go.mod
  go.sum
  pkg/api/devops/v1alpha3/groupversion_info.go
  pkg/apiserver/apiserver.go
  pkg/indexers/indexers.go
  pkg/kapis/devops/v1alpha3/pipeline/branch_filter.go
  pkg/kapis/devops/v1alpha3/pipeline/branch_filter_test.go
  pkg/kapis/devops/v1alpha3/pipelinerun/handler.go
  pkg/kapis/devops/v1alpha3/pipelinerun/util.go
  pkg/kapis/devops/v1alpha3/pipelinerun/util_test.go
  pkg/models/pipeline/pipeline.go
Labels: size/L, approved, lgtm, kind/bug

#392 Using trivy to scan the container images
  .github/workflows/build.yaml
  go.mod
  go.sum
Labels: size/L, approved, lgtm, kind/chore

#403 Always add the prefix v into the image tag name
  .github/workflows/build.yaml
Labels: approved, lgtm, size/S

#408 Fix the problem that could not proceed or break the pipeline created by others
  pkg/client/devops/pipeline.go
  pkg/client/devops/pipeline_test.go
  pkg/kapis/devops/v1alpha2/devops.go
  pkg/kapis/devops/v1alpha2/devops_test.go
Labels: approved, lgtm, size/M, kind/bug

#410 Add a PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm, size/M, kind/chore, no-changelog

#411 Correct semver pattern config for docker meta action
  .github/workflows/build.yaml
Labels: approved, lgtm, size/S, kind/bug

#418 Exclude label release-notes-none for release-drafter
  .github/release-drafter.yml
Labels: approved, lgtm, size/XS, kind/chore, release-note-none

#420 Add GitRepository Webhook Controller to manage webhooks
  cmd/controller/app/controllers.go
  cmd/controller/app/options/feature.go
  cmd/controller/app/options/feature_test.go
  config/crd/bases/devops.kubesphere.io_gitrepositories.yaml
  config/crd/bases/devops.kubesphere.io_webhooks.yaml
  config/rbac/role.yaml
  config/samples/gitRepository_webhooks/devops.yaml
  config/samples/gitRepository_webhooks/git_repository_webhook_controller.yaml
  config/samples/gitRepository_webhooks/kustomization.yaml
  config/samples/gitrepository.yaml
  config/samples/webhook.yaml
  controllers/gitrepository/gitrepository_webhook_controller.go
  controllers/gitrepository/gitrepository_webhook_controller_test.go
  docs/webhook-management.md
  docs/webhook.md
  go.mod
  go.sum
  pkg/api/devops/v1alpha1/gitrepository.go
  pkg/api/devops/v1alpha1/webhook.go
  pkg/api/devops/v1alpha1/zz_generated.deepcopy.go
  pkg/api/devops/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/addtoscheme_devops_v1alpha3.go
  pkg/client/listers/devops/v1alpha1/expansion_generated.go
  pkg/client/listers/devops/v1alpha1/gitrepository.go
  pkg/client/listers/devops/v1alpha1/s2ibinary.go
  pkg/client/listers/devops/v1alpha1/s2ibuilder.go
  pkg/client/listers/devops/v1alpha1/s2ibuildertemplate.go
  pkg/client/listers/devops/v1alpha1/s2irun.go
  pkg/client/listers/devops/v1alpha1/webhook.go
  pkg/client/listers/devops/v1alpha3/devopsproject.go
  pkg/client/listers/devops/v1alpha3/pipeline.go
Labels: kind/feature, approved, lgtm, size/XXL, tide/merge-method-squash

#423 Fix the multi-branch PipelineRun cannot be deleted
  controllers/jenkins/pipelinerun/jenkins_handler.go
  controllers/jenkins/pipelinerun/jenkins_handler_test.go
Labels: size/L, approved, lgtm, kind/bug, tide/merge-method-squash, release-note

#426 Add an override flag to the tool cmd jwt
  cmd/tools/jwt/app/configmap_updater.go
  cmd/tools/jwt/app/jwt_root.go
  cmd/tools/jwt/app/jwt_root_test.go
Labels: kind/feature, approved, lgtm, size/M, tide/merge-method-squash, release-note-none
