Repository kubesphere/ks-devops, pull requests merged in 2021-11, with the labels that each got.

#343 Provide basic E2E testing to validate whether it is normal after installing ks-devops
  .github/build-for-e2e/action.yaml
  .github/workflows/e2e.install.yaml
  test/e2e/cases/chart-install/e2e.yaml
  test/e2e/cases/chart-install/expected.yaml
  test/e2e/common/kind.yaml
Labels: kind/feature, size/L, lgtm

#346 Minor Updates in README.md
  README.md
Labels: documentation, lgtm, size/S, no-changelog

#348 Provide Kubernetes matrix E2E testing
  .github/build-for-e2e/action.yaml
  .github/e2e/action.yaml
  .github/workflows/e2e.install.yaml
  test/e2e/cases/chart-install/e2e.yaml
  test/e2e/common/kind-1.19.yaml
  test/e2e/common/kind-1.20.yaml
  test/e2e/common/kind-1.21.yaml
  test/e2e/common/kind-1.22.yaml
Labels: kind/feature, size/L, approved, lgtm

#351 Provide E2E testing documentation
  docs/README.md
  docs/e2e.md
Labels: lgtm, size/M, kind/documentation

#352 Disable CI for non code change
  .github/workflows/build.yaml
  .github/workflows/e2e.install.yaml
  .github/workflows/lint.yaml
Labels: lgtm, size/M, kind/chore, no-changelog

#357 [Codebase improvement] Reuse handlers devopsProject to devops
  pkg/kapis/devops/v1alpha3/handler.go
Labels: approved, lgtm, size/XS, no-changelog

#369 Return error when the config checking is failed in the controller cmd
  cmd/controller/app/server.go
Labels: bug, approved, lgtm, size/S, no-changelog

#370 Fix the potential panic with git multi-branch source XML parse
  pkg/client/devops/jenkins/internal/bitbucket.go
  pkg/client/devops/jenkins/internal/github.go
  pkg/client/devops/jenkins/internal/gitlab.go
  pkg/client/devops/jenkins/pipeline_internal_test.go
Labels: bug, approved, lgtm, size/XL, tide/merge-method-squash, no-changelog

#373 Bump ks cli to version v0.0.58
  config/dockerfiles/tools/Dockerfile
Labels: approved, lgtm, size/XS, kind/bug, no-changelog

#371 Fix the problem of rendering choice parameter incorrectly
  controllers/jenkins/pipeline/metadata_converter.go
  controllers/jenkins/pipeline/metadata_converter_test.go
  go.mod
  go.sum
  pkg/client/devops/jenkins/constants.go
Labels: size/L, approved, lgtm, kind/bug, tide/merge-method-squash

#374 Fix the problem of handling multi submitted input step incorrectly
  pkg/kapis/devops/v1alpha2/devops.go
Labels: lgtm, size/S, kind/bug, no-changelog

#375 Set the threshold of patch to 0% for codecov
  codecov.yml
Labels: approved, lgtm, size/XS, tide/merge-method-squash, kind/chore, no-changelog

#380 Fix the image tag name from x.x.x to vx.x.x
  .github/workflows/build.yaml
Labels: approved, lgtm, size/S, tide/merge-method-squash, kind/chore, no-changelog

#384 Fix that the controller did not use creator's token to trigger a Jenkins job
  .golangci.yml
  cmd/controller/app/controllers.go
  cmd/controller/app/options/jwt.go
  cmd/controller/app/options/options.go
  cmd/controller/app/server.go
  cmd/tools/jwt/app/jwt_root.go
  controllers/jenkins/pipelinerun/pipelinerun_controller.go
  controllers/jenkins/pipelinerun/pipelinerun_controller_test.go
  pkg/api/devops/v1alpha3/groupversion_info.go
  pkg/apiserver/authentication/authenticators/bearertoken/bearertoken.go
  pkg/jwt/token/issuer.go
  pkg/jwt/token/jwt.go
  pkg/jwt/token/jwt_test.go
  pkg/kapis/devops/v1alpha3/pipelinerun/handler.go
  pkg/models/auth/token.go
Labels: size/L, approved, lgtm, kind/bug, tide/merge-method-squash
