Repository kubesphere/ks-devops, pull requests merged in 2021-07, with the labels that each got.

#56 Fix the token verify error
  pkg/apiserver/apiserver.go
  pkg/apiserver/authentication/authenticators/bearertoken/bearertoken.go
  pkg/apiserver/authentication/token/jwt.go
  pkg/apiserver/authentication/token/jwt_test.go
  pkg/apiserver/filters/requestinfo.go
  pkg/kapis/devops/v1alpha2/handler.go
  pkg/kapis/devops/v1alpha3/handler.go
Labels: approved, lgtm, size/L

#60 Create a team in postman for ks-devops
  README.md
Labels: lgtm, size/XS

#59 Fix kubesphere.yaml broken link in the Readme file
  config/samples/kubesphere.yaml
Labels: lgtm, size/S

#69 Change the default registry to multiple registries (#61)
  README.md
  charts/ks-devops/templates/deployment-apiserver.yaml
  charts/ks-devops/templates/deployment-controller.yaml
  charts/ks-devops/values.yaml
Labels: lgtm, size/S

#71 Extract authentication jwtSecret as a variable
  charts/ks-devops/templates/config.yaml
  charts/ks-devops/templates/deployment-apiserver.yaml
  charts/ks-devops/values.yaml
Labels: lgtm, size/XS

#78 Fix the userInfo is nil
  pkg/kapis/devops/v1alpha2/devops.go
Labels: approved, lgtm, size/M

#79 update readme for Fix the token verify error
  README.md
Labels: approved, lgtm, size/XS

#74 Extract agent builder and s2i image's docker registry
  charts/ks-devops/charts/jenkins/README.md
  charts/ks-devops/charts/jenkins/templates/jenkins-casc-config.yml
  charts/ks-devops/charts/jenkins/values.yaml
  charts/ks-devops/charts/s2i/README.md
  charts/ks-devops/charts/s2i/templates/_helpers.tpl
  charts/ks-devops/charts/s2i/templates/binary.yaml
  charts/ks-devops/charts/s2i/templates/java.yaml
  charts/ks-devops/charts/s2i/templates/nodejs.yaml
  charts/ks-devops/charts/s2i/templates/operator.yaml
  charts/ks-devops/charts/s2i/templates/python.yaml
  charts/ks-devops/charts/s2i/templates/tomcat.yaml
  charts/ks-devops/charts/s2i/values.yaml
Labels: lgtm, size/L

#75 Reload Jenkins CasC in Jenkins Config Controller
  cmd/controller/app/controllers.go
  controllers/jenkinsconfig/jenkinsconfig_controller.go
  pkg/client/devops/configuration.go
  pkg/client/devops/fake/fakedevops.go
  pkg/client/devops/interface.go
  pkg/client/devops/jenkins/configuration.go
  pkg/client/devops/jenkins/devops.go
  pkg/client/devops/jenkins/options.go
Labels: lgtm, size/M

#80 Avoid the error output be hidden
  pkg/client/devops/jenkins/build.go
  pkg/kapis/devops/v1alpha2/register.go
  pkg/kapis/devops/v1alpha2/sonarqube.go
Labels: approved, lgtm, size/L
