Repository kubesphere/ks-devops, pull requests merged in 2022-12, with the labels that each got.

#860 Remove queued status for pipelinerun #859
  controllers/jenkins/pipelinerun/utils.go
Labels: approved, lgtm, size/XS, release-note

#868 fix test for remove queue status
  controllers/jenkins/pipelinerun/utils_test.go
Labels: approved, lgtm, size/S

#870 fix test for remove queue status
  controllers/jenkins/pipelinerun/utils_test.go
Labels: approved, lgtm, size/S

#869 update ks-tool to 0.0.70
  config/dockerfiles/tools/Dockerfile
Labels: approved, lgtm, size/XS, kind/bug, kind/flake
