Repository kubesphere/ks-devops, pull requests merged in 2022-04, with the labels that each got.

#529 Fix the restful doc of the v1alpha3
  pkg/kapis/devops/v1alpha3/register.go
Labels: approved, size/S, kind/bug, release-note-none

#532 Fix the gitrepository update API cannot change the annotations
  config/rbac/role.yaml
  pkg/kapis/devops/v1alpha3/scm/gitrepository_handler.go
  pkg/kapis/devops/v1alpha3/scm/route.go
Labels: approved, size/S, kind/bug, release-note-none

#535 Fix the conflicts with duplicated PipelineRuns
  controllers/jenkins/pipelinerun/pipelinerun_synchronizer.go
  controllers/jenkins/pipelinerun/pipelinerun_synchronizer_test.go
  pkg/kapis/devops/v1alpha3/webhook/register_test.go
  pkg/kapis/devops/v1alpha3/webhook/workflowrun_handler.go
  pkg/kapis/devops/v1alpha3/webhook/workflowrun_handler_test.go
Labels: size/L, approved, do-not-merge/release-note-label-needed

#540 Bump golangci lint action to v3
  .github/workflows/lint.yaml
Labels: approved, size/XS, kind/bug, release-note-none

#541 The AppProject CR should be in the argocd namespace
  cmd/controller/app/controllers.go
  controllers/argocd/project_controller.go
  controllers/argocd/project_controller_test.go
Labels: approved, size/M, kind/bug, release-note-none

#542 Add Argo CD application cascade deletion support
  controllers/argocd/application_controller.go
  controllers/argocd/application_controller_test.go
  pkg/api/gitops/v1alpha1/constants.go
  pkg/kapis/gitops/v1alpha1/argocd/handler.go
  pkg/kapis/gitops/v1alpha1/argocd/route.go
  pkg/kapis/gitops/v1alpha1/argocd/route_test.go
Labels: kind/feature, size/L, approved, release-note-none

#545 Always return the host cluster info in the cluster list API
  pkg/kapis/gitops/v1alpha1/argocd/handler.go
  pkg/kapis/gitops/v1alpha1/argocd/route_test.go
Labels: approved, size/S, kind/bug, release-note-none

#546 Fix the potential duplicated Argo Apps
  controllers/argocd/application_controller.go
Labels: approved, size/M, kind/bug, release-note-none

#530 Avoid to return the secret text from API
  pkg/models/devops/devops.go
Labels: approved, size/XS, do-not-merge/hold, release-note-none

#533 Support dynamic parameters with configmap data
  config/crd/bases/devops.kubesphere.io_pipelineruns.yaml
  config/crd/bases/devops.kubesphere.io_pipelines.yaml
  go.mod
  go.sum
  pkg/api/devops/v1alpha3/pipeline_types.go
  pkg/kapis/devops/v1alpha3/handler.go
  pkg/kapis/devops/v1alpha3/pipeline/handler.go
  pkg/kapis/devops/v1alpha3/register.go
  pkg/kapis/devops/v1alpha3/register_test.go
  pkg/models/devops/devops.go
  pkg/models/devops/devops_test.go
Labels: kind/feature, approved, size/XL, tide/merge-method-squash, release-note

#555 Dynamic parameters: fix isQuoted optional
  config/crd/bases/devops.kubesphere.io_pipelineruns.yaml
  config/crd/bases/devops.kubesphere.io_pipelines.yaml
  pkg/api/devops/v1alpha3/pipeline_types.go
Labels: approved, lgtm, size/XS, kind/bug, release-note-none

#559 Fix CVE-2022-27191
  go.mod
  go.sum
Labels: approved, lgtm, size/S, kind/bug, release-note

#560 Revert dynamic parameters due to jenkins issues
  config/crd/bases/devops.kubesphere.io_pipelineruns.yaml
  pkg/api/devops/v1alpha3/pipeline_types.go
  pkg/client/clientset/versioned/typed/devops/v1alpha3/pipeline.go
  pkg/kapis/devops/v1alpha3/handler.go
  pkg/kapis/devops/v1alpha3/register.go
  pkg/kapis/devops/v1alpha3/register_test.go
  pkg/models/devops/devops.go
  pkg/models/devops/devops_test.go
Labels: size/L, approved, kind/cleanup, release-note-none

#562 Fix the wrong YAML parse of the Argo Cluster
  controllers/argocd/multi-cluster-controller.go
  controllers/argocd/multi-cluster-controller_test.go
  controllers/argocd/types.go
  controllers/argocd/types_test.go
Labels: size/S, kind/bug, release-note-none

#571 Auto amend the Gitlab URL
  cmd/controller/app/controllers.go
  cmd/controller/app/options/feature.go
  cmd/controller/app/options/feature_test.go
  controllers/core/fake.go
  controllers/core/named.go
  controllers/core/named_test.go
  controllers/gitrepository/constants.go
  controllers/gitrepository/gitrepository_amend_controller.go
  controllers/gitrepository/gitrepository_amend_controller_test.go
  controllers/gitrepository/gitrepository_webhook_controller.go
  controllers/gitrepository/register.go
  controllers/gitrepository/register_test.go
  controllers/gitrepository/webhook_notify.go
Labels: size/L, release-note-none

#574 Fix the CD manual sync not work
  controllers/argocd/application_controller.go
  controllers/argocd/application_controller_test.go
Labels: size/S, kind/bug, release-note-none
