Repository kubesphere/ks-devops, pull requests merged in 2022-06, with the labels that each got.

#641 remove unused method parameters
  cmd/controller/app/controllers.go
Labels: approved, lgtm, size/XS, kind/cleanup, release-note-none

#647 Create a FAQ document
  docs/faq.md
Labels: size/XS, kind/documentation, release-note-none

#597 Add SCM webhook to trigger Pipelines
  docs/webhook.md
  pkg/api/devops/v1alpha3/last_changes.go
  pkg/api/devops/v1alpha3/last_changes_test.go
  pkg/api/devops/v1alpha3/pipeline_types.go
  pkg/api/devops/v1alpha3/pipeline_types_test.go
  pkg/apiserver/apiserver.go
  pkg/jwt/token/fake_issuer.go
  pkg/jwt/token/fake_issuer_test.go
  pkg/kapis/devops/v1alpha3/pipelinerun/util.go
  pkg/kapis/devops/v1alpha3/pipelinerun/util_test.go
  pkg/kapis/devops/v1alpha3/register.go
  pkg/kapis/devops/v1alpha3/register_test.go
  pkg/kapis/devops/v1alpha3/webhook/register.go
  pkg/kapis/devops/v1alpha3/webhook/register_test.go
  pkg/kapis/devops/v1alpha3/webhook/scm.go
  pkg/kapis/devops/v1alpha3/webhook/scm_test.go
  pkg/models/pipeline/pipeline.go
  pkg/models/pipeline/pipeline_test.go
Labels: size/XXL, release-note

#603 Add a draft desgin of the pipeline steps
  docs/customize-pipeline-steps.md
Labels: size/M, kind/documentation, release-note

#645 Provide a document for the pressure testing
  docs/testing.md
Labels: size/S, kind/documentation, release-note-none

#651 Add an API for accessing the clusterStepTemplates
  config/crd/bases/devops.kubesphere.io_clustersteptemplates.yaml
  config/crd/bases/devops.kubesphere.io_pipelines.yaml
  config/samples/devops_v1alpha3_steptemplate.yaml
  docs/README.md
  pkg/api/devops/v1alpha3/steptemplate_types.go
  pkg/api/devops/v1alpha3/zz_generated.deepcopy.go
  pkg/kapis/devops/v1alpha3/register.go
  pkg/kapis/devops/v1alpha3/steptemplate/handler.go
  pkg/kapis/devops/v1alpha3/steptemplate/handler_test.go
  pkg/kapis/devops/v1alpha3/steptemplate/route.go
  pkg/kapis/devops/v1alpha3/steptemplate/route_test.go
Labels: kind/feature, size/XL, release-note-none

#654 Support to do the API testing
  .github/workflows/api-testing.yaml
  .gitignore
  Makefile
  config/crd/kustomization.yaml
  config/default/kustomization.yaml
  config/manager/apiserver-service.yaml
  config/manager/apiserver.yaml
  config/manager/config.yaml
  config/manager/kustomization.yaml
  config/manager/nameReference.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  test/api/data/devops_v1alpha3_steptemplate.yaml
  test/api/testcase-1.yaml
  test/api/testcase-2.yaml
  test/api/testcase-render.yaml
Labels: size/L, release-note-none, kind/test

#655 Condition is always 'true' because 'user' is always not 'nil'
  pkg/kapis/devops/v1alpha3/pipelinerun/handler.go
  pkg/kapis/devops/v1alpha3/pipelinerun/handler_test.go
Labels: size/L, approved, kind/cleanup, release-note-none

#662 Avoid using the initial Jenkins fake token
  pkg/client/devops/jenkins/options.go
Labels: size/XS, kind/bug, release-note-none

#670 Using a new API to fetch both public and private repos of a user
  pkg/kapis/devops/v1alpha3/scm/scmhandler.go
  pkg/kapis/devops/v1alpha3/scm/scmhandler_test.go
Labels: size/XS, kind/bug, release-note-none

#658 Support to render step templates via CLI
  Makefile
  cmd/tools/tpl/README.md
  cmd/tools/tpl/render.go
  cmd/tools/tpl/root.go
  pkg/api/devops/v1alpha3/steptemplate_render.go
  pkg/api/devops/v1alpha3/steptemplate_render_test.go
  pkg/api/devops/v1alpha3/steptemplate_types.go
  pkg/kapis/devops/v1alpha3/steptemplate/handler.go
  pkg/kapis/devops/v1alpha3/steptemplate/route_test.go
Labels: kind/feature, size/L, release-note-none

#683 typo fix: annotation->annotations
  controllers/jenkins/config/README.md
Labels: lgtm, size/XS, kind/chore, release-note-none

#681 Support to copy argocd-related annotations and labels
  controllers/argocd/application_controller.go
  controllers/argocd/application_controller_test.go
Labels: kind/feature, size/L, release-note-none
