Repository kubesphere/ks-devops, pull requests merged in 2022-09, with the labels that each got.

#808 Fixed: Skip github build status notifications
  config/crd/bases/devops.kubesphere.io_pipelineruns.yaml
  config/crd/bases/devops.kubesphere.io_pipelines.yaml
  pkg/api/devops/v1alpha3/pipeline_types.go
  pkg/client/devops/jenkins/internal/bitbucket.go
  pkg/client/devops/jenkins/internal/common_test.go
  pkg/client/devops/jenkins/internal/github.go
  pkg/client/devops/jenkins/internal/gitlab.go
Labels: size/L, approved, release-note-none

#812 Fix error sync credential
  go.mod
  go.sum
  pkg/client/devops/jclient/credential.go
  pkg/client/devops/jclient/credential_test.go
Labels: approved, lgtm, size/S, kind/bug, release-note-none

#810 Fix the webhook settings doc errors
  docs/webhook.md
  pkg/kapis/devops/v1alpha3/webhook/scm.go
Labels: size/M, kind/documentation, release-note-none

#815 Support pod template privileged setting
  go.mod
  go.sum
Labels: size/S, kind/chore, release-note-none

#813 Fix nil pointer issue when building helmchart
  controllers/fluxcd/application-controller.go
  controllers/fluxcd/application-controller_test.go
Labels: approved, size/M, kind/bug, release-note-none

#816 Run PR build with Jenkinsfile instead of GitHub Actions
  .github/Jenkinsfile
  .github/workflows/build.yaml
  .github/workflows/ci-check-license.yaml.bak
  .github/workflows/lint.yaml.bak
Labels: size/M, kind/chore, release-note-none

#814 Change the FluxApp field in ApplicationStatus
  config/crd/bases/gitops.kubesphere.io_applications.yaml
  pkg/api/gitops/v1alpha1/application.go
  pkg/api/gitops/v1alpha1/zz_generated.deepcopy.go
Labels: kind/feature, size/L, approved, kind/design, release-note-none

#818 Avoid pipeline running status order override
  .github/Jenkinsfile
  controllers/gitrepository/gitrepository_webhook_controller.go
  controllers/gitrepository/pull_request_status_controller.go
  controllers/gitrepository/pull_request_status_controller_test.go
  controllers/gitrepository/testdata/statuses.json
  pkg/utils/stringutils/error.go
  pkg/utils/stringutils/error_test.go
Labels: size/XL, kind/bug, release-note-none

#823 fix(api/jenkins): fix jenkins connection hang if set maxconnction zero
  pkg/client/devops/jenkins/jenkins.go
Labels: approved, size/XS, kind/bug, do-not-merge/release-note-label-needed

#825 Support to store PipelineRun data into ConfigMap
  Makefile
  cmd/controller/app/options/feature.go
  cmd/controller/app/options/feature_test.go
  controllers/jenkins/pipelinerun/pipelinerun_controller.go
  controllers/jenkins/pipelinerun/pipelinerun_controller_test.go
  pkg/kapis/devops/v1alpha3/pipelinerun/handler.go
  pkg/kapis/devops/v1alpha3/pipelinerun/handler_test.go
  pkg/store/configmap/pipelinerun.go
  pkg/store/configmap/pipelinerun_test.go
  pkg/store/fake/fake_core_test.go
  pkg/store/fake/fake_store.go
  pkg/store/store/types.go
  pkg/store/store/types_test.go
Labels: kind/feature, size/XL, release-note

#817 Add Status for FluxApp
  cmd/controller/app/controllers.go
  controllers/fluxcd/constants.go
  controllers/fluxcd/fluxcd-application-status-controller.go
  controllers/fluxcd/fluxcd-application-status-controller_test.go
  pkg/external/fluxcd/helm/v2beta1/condition_types.go
  pkg/external/fluxcd/kustomize/v1beta2/condition_types.go
  pkg/external/fluxcd/meta/conditions.go
Labels: kind/feature, approved, size/XXL, kind/design, release-note-none

#832 Change cluster secret label
  controllers/fluxcd/multi-cluster-controller.go
Labels: approved, lgtm, size/XS, kind/design, release-note-none

#831 clean-up: Move ArgoCDOption into apiserverconfig
  cmd/apiserver/app/server.go
  pkg/config/config.go
Labels: approved, lgtm, size/XS, kind/cleanup, release-note-none

#830 Organize all devops related projects into a table
  docs/projects.md
Labels: size/S, release-note-none
