Repository kubesphere/ks-devops, pull requests merged in 2022-07, with the labels that each got.

#684 Provide a documentation of the image updater
  docs/image-automation.md
Labels: size/L, kind/documentation, release-note-none

#703 Support the basic image updater feature base on Argo
  .licenserc.yaml
  cmd/controller/app/controllers.go
  config/crd/bases/devops.kubesphere.io_clustersteptemplates.yaml
  config/crd/bases/gitops.kubesphere.io_imageupdaters.yaml
  config/rbac/role.yaml
  config/samples/gitops/application.yaml
  config/samples/gitops/image-updater.yaml
  controllers/argocd/argocd-application-status-controller.go
  controllers/argocd/argocd-application-status-controller_test.go
  controllers/argocd/data/argo-status-without-summary.json
  controllers/argocd/data/argo-status.json
  controllers/argocd/image-updater-controller.go
  controllers/argocd/image-updater-controller_test.go
  controllers/argocd/interface_test.go
  go.mod
  go.sum
  pkg/api/gitops/v1alpha1/constants.go
  pkg/api/gitops/v1alpha1/image-updater.go
  pkg/api/gitops/v1alpha1/image-updater_test.go
  pkg/api/gitops/v1alpha1/zz_generated.deepcopy.go
  test/api/README.md
Labels: size/XXL, release-note-none

#726 Skip CVE-2022-1996 for now due to it might cause too many changes
  .github/workflows/.trivyignore
  .github/workflows/build.yaml
Labels: size/S, release-note-none

#724 Avoid using Jenkins API to convert Jenkinsfile format
  cmd/controller/app/controllers.go
  controllers/jenkins/pipeline/constants.go
  controllers/jenkins/pipeline/interface_test.go
  controllers/jenkins/pipeline/json_converter.go
  controllers/jenkins/pipeline/json_converter_test.go
  controllers/jenkins/pipeline/metadata_converter_test.go
  go.mod
  go.sum
  pkg/api/devops/v1alpha3/pipeline_types.go
  pkg/kapis/devops/v1alpha3/handler.go
  pkg/kapis/devops/v1alpha3/register.go
  pkg/kapis/devops/v1alpha3/register_test.go
  pkg/models/devops/devops.go
  pkg/models/devops/devops_test.go
Labels: size/XL, kind/api-change, release-note-none

#741 Added test cases for pipeline_matadata_controller.
  controllers/jenkins/pipeline/pipeline_metadata_controller_test.go
  controllers/jenkins/pipeline/setup_test.go
Labels: size/L, lgtm, kind/cleanup, release-note-none

#742 Set a generic response for the jenkinsfile update API
  pkg/kapis/devops/v1alpha3/handler.go
  pkg/kapis/devops/v1alpha3/register.go
  pkg/kapis/devops/v1alpha3/register_test.go
  pkg/models/devops/devops.go
Labels: size/L, kind/cleanup, release-note-none

#680 Add Git Repository Support for FluxCD
  cmd/controller/app/controllers.go
  config/rbac/role.yaml
  controllers/fluxcd/git-repository-controller.go
  controllers/fluxcd/git-repository-controller_test.go
  pkg/api/gitops/v1alpha1/constants.go
Labels: kind/feature, approved, size/XL, kind/design, do-not-merge/release-note-label-needed

#744 Update the contribution guide to make it be easier run locally
  CONTRIBUTING.md
Labels: approved, size/S, kind/documentation, release-note-none

#746 Make the Pipeline edit mode be specific
  controllers/jenkins/pipeline/json_converter.go
  controllers/jenkins/pipeline/json_converter_test.go
  go.mod
  go.sum
  pkg/api/devops/v1alpha3/pipeline_types.go
Labels: size/M, kind/bug, release-note-none

#747 Fix jenkins edit mode
  pkg/models/devops/devops.go
  pkg/models/devops/devops_test.go
Labels: size/M, kind/bug, release-note-none

#748 Support to get Jenkins agent labels from ConfigMap
  cmd/controller/app/controllers.go
  controllers/argocd/application_controller_test.go
  controllers/argocd/argocd-application-status-controller_test.go
  controllers/argocd/git-repository-controller_test.go
  controllers/argocd/image-updater-controller_test.go
  controllers/argocd/multi-cluster-controller_test.go
  controllers/argocd/project_controller_test.go
  controllers/core/fake.go
  controllers/core/fake_manager.go
  controllers/core/fake_manager_test.go
  controllers/core/fake_test.go
  controllers/jenkins/config/interface_test.go
  controllers/jenkins/config/labels_controller.go
  controllers/jenkins/config/labels_controller_test.go
  go.mod
  go.sum
  pkg/api/devops/constants.go
  pkg/kapis/devops/v1alpha3/handler.go
  pkg/kapis/devops/v1alpha3/handler_test.go
  pkg/kapis/devops/v1alpha3/register.go
  pkg/kapis/devops/v1alpha3/register_test.go
  pkg/models/devops/common.go
  pkg/models/devops/common_test.go
  pkg/models/devops/devops.go
  pkg/models/devops/devops_test.go
  pkg/models/devops/jkerror_test.go
  pkg/models/devops/project_credential_handler_test.go
  pkg/models/devops/project_pipeline_sonar_handler_test.go
  pkg/models/devops/s2ibinary_handler_test.go
Labels: kind/feature, size/XXL, kind/api-change, release-note

#756 Add more fields into the git repository crd
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/init.sh
  Makefile
  config/crd/bases/devops.kubesphere.io_gitrepositories.yaml
  config/crd/bases/devops.kubesphere.io_pipelineruns.yaml
  config/crd/bases/devops.kubesphere.io_pipelines.yaml
  config/rbac/role.yaml
  config/samples/gitrepository.yaml
  controllers/gitrepository/gitrepository_amend_controller.go
  controllers/gitrepository/gitrepository_amend_controller_test.go
  controllers/gitrepository/gitrepository_webhook_controller.go
  controllers/gitrepository/gitrepository_webhook_controller_test.go
  controllers/gitrepository/interface_test.go
  controllers/gitrepository/testdata/hook.json
  controllers/gitrepository/testdata/hooks.json
  controllers/gitrepository/webhook_notify_test.go
  controllers/template/clustertemplate_controller.go
  controllers/template/template_controller.go
  pkg/api/devops/v1alpha3/gitrepository.go
  pkg/api/devops/v1alpha3/zz_generated.deepcopy.go
Labels: kind/feature, size/XXL, release-note-none

#750 Add a document about the API permission
  docs/README.md
  docs/permission.md
Labels: size/S, kind/documentation, release-note-none
