Repository kubesphere/ks-devops, pull requests merged in 2022-02, with the labels that each got.

#451 Support to install addon with CRD
  .golangci.yml
  Makefile
  cmd/controller/app/controllers.go
  cmd/controller/app/server.go
  config/crd/bases/devops.kubesphere.io_addons.yaml
  config/crd/bases/devops.kubesphere.io_addonstrategies.yaml
  config/rbac/fake_editor_role.yaml
  config/rbac/fake_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/addon/argocd.yaml
  config/samples/addon/argocd_simple_operator.yaml
  config/samples/addon/ks_releaser.yaml
  config/samples/addon/ks_releaser_simple_operator.yaml
  controllers/addon/addon_controller.go
  controllers/addon/addon_controller_test.go
  controllers/addon/operator_controller.go
  controllers/addon/operator_controller_test.go
  controllers/fake_controller.go
  controllers/jenkins/config/README.md
  controllers/jenkins/pipelinerun/pipelinerun_controller.go
  docs/README.md
  docs/addon.md
  go.mod
  pkg/api/devops/v1alpha1/addon.go
  pkg/api/devops/v1alpha1/addon_strategy.go
  pkg/api/devops/v1alpha1/addon_strategy_test.go
  pkg/api/devops/v1alpha1/zz_generated.deepcopy.go
  pkg/utils/k8sutil/k8sutil_test.go
  pkg/utils/k8sutil/objectmeta.go
  pkg/utils/k8sutil/objectmeta_test.go
  pkg/utils/sliceutil/sliceutils.go
  pkg/utils/sliceutil/sliceutils_test.go
Labels: kind/feature, approved, lgtm, size/XXL, tide/merge-method-squash, release-note

#459 Re-orgnize the controllers package
  PROJECT
  cmd/controller/app/controllers.go
  cmd/controller/app/options/feature.go
  cmd/controller/app/options/feature_test.go
  controllers/README.md
  controllers/jenkins/README.md
  controllers/jenkins/devopscredential/devopscredential_controller.go
  controllers/jenkins/devopscredential/devopscredential_controller_test.go
  controllers/jenkins/devopsproject/devopsproject_controller.go
  controllers/jenkins/devopsproject/devopsproject_controller_test.go
  controllers/jenkins/pipeline/pipeline_controller.go
  controllers/jenkins/pipeline/pipeline_controller_test.go
  pkg/api/devops/v1alpha3/fake_types.go
  pkg/api/devops/v1alpha3/zz_generated.deepcopy.go
Labels: size/L, approved, lgtm, tide/merge-method-squash, kind/chore, release-note-none

#462 Add ClusterTemplate API support
  PROJECT
  config/crd/bases/devops.kubesphere.io_clustertemplates.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_clustertemplates.yaml
  config/crd/patches/webhook_in_clustertemplates.yaml
  config/rbac/clustertemplate_editor_role.yaml
  config/rbac/clustertemplate_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/devops_v1alpha1_clustertemplate.yaml
  controllers/suite_test.go
  controllers/template/clustertemplate_controller.go
  controllers/template/template_controller.go
  docs/pipeline-template.md
  pkg/api/devops/v1alpha1/clustertemplate_types.go
  pkg/api/devops/v1alpha1/zz_generated.deepcopy.go
Labels: kind/feature, size/L, approved, lgtm, tide/merge-method-squash, release-note-none

#461 Refine Swagger config to access Swagger UI in development environment
  config/dockerfiles/apiserver/Dockerfile
  docs/swagger.md
  pkg/kapis/doc/registry.go
Labels: approved, lgtm, size/M, kind/bug, tide/merge-method-squash, release-note-none

#463 Add Argo CD support to DevOpsProject CRD
  cmd/controller/app/controllers.go
  config/crd/bases/devops.kubesphere.io_devopsprojects.yaml
  config/rbac/role.yaml
  controllers/argocd/project_controller.go
  controllers/argocd/project_controller_test.go
  controllers/core/named.go
  pkg/api/devops/v1alpha3/devopsproject_types.go
  pkg/api/devops/v1alpha3/zz_generated.deepcopy.go
  pkg/utils/k8sutil/k8sutil.go
  pkg/utils/k8sutil/k8sutil_test.go
Labels: kind/feature, approved, lgtm, size/XXL, tide/merge-method-squash, release-note-none

#464 Add missing rbac annotation of the devopsProject controller
  config/rbac/role.yaml
  controllers/jenkins/devopsproject/devopsproject_controller.go
Labels: approved, lgtm, size/S, tide/merge-method-squash, kind/chore, release-note-none

#466 Add argo cd application support (controller part)
  cmd/controller/app/controllers.go
  config/crd/bases/devops.kubesphere.io_applications.yaml
  config/rbac/role.yaml
  config/samples/devops_v1alpha1_application.yaml
  config/samples/devops_v1alpha3_fake.yaml
  controllers/argocd/application_controller.go
  controllers/argocd/application_controller_test.go
  controllers/argocd/constants.go
  controllers/argocd/project_controller.go
  pkg/api/devops/v1alpha1/application.go
  pkg/api/devops/v1alpha1/zz_generated.deepcopy.go
  pkg/utils/k8sutil/k8sutil.go
  pkg/utils/k8sutil/k8sutil_test.go
Labels: kind/feature, approved, size/XXL, release-note-none

#467 Add API for the application custom resource
  pkg/kapis/devops/v1alpha1/argocd/handler.go
  pkg/kapis/devops/v1alpha1/argocd/handler_test.go
  pkg/kapis/devops/v1alpha1/argocd/route.go
  pkg/kapis/devops/v1alpha1/argocd/route_test.go
  pkg/kapis/devops/v1alpha1/common/options.go
  pkg/kapis/devops/v1alpha1/register.go
  pkg/kapis/devops/v1alpha1/template/handler.go
  pkg/kapis/devops/v1alpha1/template/handler_test.go
  pkg/kapis/devops/v1alpha1/template/route.go
Labels: kind/feature, approved, lgtm, size/XL, tide/merge-method-squash, release-note-none

#472 Add a check list into the pull request template
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: approved, lgtm, size/XS, kind/chore, release-note-none

#469 Support sync kubesphere multi-cluster to argo multi-cluster
  cmd/controller/app/controllers.go
  controllers/argocd/multi-cluster-controller.go
  controllers/argocd/multi-cluster-controller_test.go
  controllers/argocd/types.go
  controllers/argocd/types_test.go
Labels: kind/feature, approved, lgtm, size/XL, tide/merge-method-squash, release-note-none

#474 Add an API for getting the argo cluster list
  pkg/kapis/devops/v1alpha1/argocd/handler.go
  pkg/kapis/devops/v1alpha1/argocd/route.go
  pkg/kapis/devops/v1alpha1/argocd/route_test.go
Labels: kind/feature, size/L, approved, lgtm, tide/merge-method-squash, release-note-none

#476 Add API of listing organizations and repositories
  pkg/apiserver/apiserver.go
  pkg/client/git/message.go
  pkg/kapis/devops/v1alpha2/register.go
  pkg/kapis/devops/v1alpha3/register.go
  pkg/kapis/devops/v1alpha3/register_test.go
  pkg/kapis/devops/v1alpha3/scm/route.go
  pkg/kapis/devops/v1alpha3/scm/scmhandler.go
  pkg/kapis/devops/v1alpha3/scm/scmhandler_test.go
  pkg/kapis/devops/v1alpha3/scm/testdata/orgs.json
  pkg/kapis/devops/v1alpha3/scm/testdata/repos.json
  pkg/kapis/devops/v1alpha3/scm/types.go
Labels: kind/feature, approved, lgtm, size/XL, tide/merge-method-squash, release-note-none

#478 Move CRD application into a new group gitops
  Makefile
  PROJECT
  config/crd/bases/devops.kubesphere.io_fakes.yaml
  config/crd/bases/gitops.kubesphere.io_applications.yaml
  config/rbac/role.yaml
  controllers/argocd/application_controller.go
  controllers/argocd/application_controller_test.go
  pkg/api/devops/v1alpha1/clustertemplate_types.go
  pkg/api/devops/v1alpha1/template_interface.go
  pkg/api/devops/v1alpha1/zz_generated.deepcopy.go
  pkg/api/gitops/v1alpha1/application.go
  pkg/api/gitops/v1alpha1/groupversion_info.go
  pkg/api/gitops/v1alpha1/groupversion_info_test.go
  pkg/api/gitops/v1alpha1/zz_generated.deepcopy.go
  pkg/apiserver/apiserver.go
  pkg/kapis/common/options.go
  pkg/kapis/devops/v1alpha1/register.go
  pkg/kapis/devops/v1alpha1/register_test.go
  pkg/kapis/devops/v1alpha1/template/handler.go
  pkg/kapis/devops/v1alpha1/template/handler_test.go
  pkg/kapis/devops/v1alpha1/template/route.go
  pkg/kapis/devops/v1alpha1/template/template_handler.go
  pkg/kapis/devops/v1alpha1/template/template_handler_test.go
  pkg/kapis/gitops/v1alpha1/argocd/handler.go
  pkg/kapis/gitops/v1alpha1/argocd/handler_test.go
  pkg/kapis/gitops/v1alpha1/argocd/route.go
  pkg/kapis/gitops/v1alpha1/argocd/route_test.go
  pkg/kapis/gitops/v1alpha1/registery.go
Labels: approved, lgtm, size/XXL, tide/merge-method-squash, kind/chore, release-note-none

#477 Move templates types to v1alpha3
  config/crd/bases/devops.kubesphere.io_clustertemplates.yaml
  config/crd/bases/devops.kubesphere.io_templates.yaml
  controllers/template/clustertemplate_controller.go
  controllers/template/template_controller.go
  pkg/api/devops/v1alpha1/zz_generated.deepcopy.go
  pkg/api/devops/v1alpha3/clustertemplate_types.go
  pkg/api/devops/v1alpha3/template_interface.go
  pkg/api/devops/v1alpha3/template_types.go
  pkg/api/devops/v1alpha3/zz_generated.deepcopy.go
  pkg/apiserver/apiserver.go
  pkg/kapis/devops/v1alpha1/register.go
  pkg/kapis/devops/v1alpha3/common/options.go
  pkg/kapis/devops/v1alpha3/register.go
  pkg/kapis/devops/v1alpha3/template/cluster_template_handler.go
  pkg/kapis/devops/v1alpha3/template/cluster_template_handler_test.go
  pkg/kapis/devops/v1alpha3/template/handler.go
  pkg/kapis/devops/v1alpha3/template/handler_test.go
  pkg/kapis/devops/v1alpha3/template/render.go
  pkg/kapis/devops/v1alpha3/template/render_test.go
  pkg/kapis/devops/v1alpha3/template/route.go
  pkg/kapis/devops/v1alpha3/template/route_test.go
  pkg/kapis/devops/v1alpha3/template/template_handler.go
  pkg/kapis/devops/v1alpha3/template/template_handler_test.go
Labels: approved, lgtm, size/XL, tide/merge-method-squash, kind/api-change, release-note-none
