Repository kubesphere/ks-devops, pull requests merged in 2022-08, with the labels that each got.

#770 fix variable typo
  cmd/controller/app/controllers.go
Labels: approved, size/XS, kind/cleanup, do-not-merge/release-note-label-needed

#771 Add unit test case for flux/git-repository-controller
  controllers/fluxcd/git-repository-controller_test.go
Labels: size/M, kind/cleanup, release-note-none

#768 Support to render step templates in JSON format
  Makefile
  cmd/controller/app/controllers.go
  config/crd/bases/devops.kubesphere.io_clustersteptemplates.yaml
  config/rbac/role.yaml
  controllers/fluxcd/git-repository-controller_test.go
  go.mod
  go.sum
  pkg/api/devops/v1alpha3/steptemplate_render.go
  pkg/api/devops/v1alpha3/steptemplate_render_test.go
  pkg/api/devops/v1alpha3/steptemplate_types.go
  pkg/api/devops/v1alpha3/testdata/credential-kubeconfig.json
  pkg/api/devops/v1alpha3/testdata/credential-ssh.json
  pkg/api/devops/v1alpha3/testdata/credential-string.json
  pkg/api/devops/v1alpha3/testdata/docker-login.json
  pkg/api/devops/v1alpha3/testdata/dsl-echo.json
  pkg/api/devops/v1alpha3/testdata/sh-echo.json
  pkg/kapis/devops/v1alpha3/steptemplate/handler.go
  pkg/kapis/devops/v1alpha3/steptemplate/route.go
  pkg/kapis/devops/v1alpha3/steptemplate/route_test.go
  pkg/models/resources/v1alpha3/devops/devops.go
  pkg/models/resources/v1alpha3/interface.go
  pkg/models/resources/v1alpha3/interface_test.go
  pkg/models/resources/v1alpha3/listhandler_test.go
  pkg/models/resources/v1alpha3/namedHandler.go
  pkg/models/resources/v1alpha3/namedHandler_test.go
Labels: kind/feature, size/XL, release-note-none

#781 Add more unit tests
  .golangci.yml
  pkg/apis/apis_test.go
  pkg/client/k8s/kubernetes.go
  pkg/client/k8s/kubernetes_test.go
  pkg/client/k8s/null_client.go
  pkg/client/k8s/options_test.go
  pkg/client/sonarqube/interface.go
  pkg/client/sonarqube/interface_test.go
  pkg/client/sonarqube/options.go
  pkg/client/sonarqube/options_test.go
  pkg/client/sonarqube/sonarqube.go
  pkg/client/sonarqube/sonarqube_test.go
  pkg/indexers/indexers.go
  pkg/indexers/indexers_test.go
  pkg/kapis/devops/v1alpha2/register_test.go
  pkg/models/auth/token.go
  pkg/models/auth/token_test.go
  pkg/models/devops/project_pipeline_sonar_handler.go
Labels: size/XL, kind/chore, release-note-none

#782 Add a field to indicate desired agent
  config/crd/bases/devops.kubesphere.io_clustersteptemplates.yaml
  pkg/api/devops/v1alpha3/steptemplate_types.go
Labels: size/XS, release-note-none

#784 Fix the Jenkins cron expression check error
  pkg/client/devops/jenkins/devops_test.go
  pkg/client/devops/jenkins/pipeline.go
Labels: size/M, kind/bug, release-note-none

#786 Upgrade go-scm to v1.11.19
  controllers/gitrepository/gitrepository_webhook_controller.go
  go.mod
  go.sum
  pkg/kapis/devops/v1alpha3/scm/scmhandler.go
Labels: size/S, release-note-none

#787 Add a condition field to the step template
  config/crd/bases/devops.kubesphere.io_clustersteptemplates.yaml
  pkg/api/devops/v1alpha3/steptemplate_types.go
Labels: size/XS, release-note-none

#791 Support object in the step paramters
  cmd/tools/tpl/render.go
  codecov.yml
  pkg/api/devops/v1alpha3/steptemplate_render.go
  pkg/api/devops/v1alpha3/steptemplate_render_test.go
  pkg/api/devops/v1alpha3/testdata/docker-login.json
  pkg/jwt/token/jwt.go
  pkg/jwt/token/jwt_test.go
  pkg/kapis/devops/v1alpha3/steptemplate/handler.go
Labels: size/M, kind/chore, release-note-none

#792 chore: Update Makefile
  Makefile
Labels: approved, lgtm, size/XS, kind/chore, release-note-none

#794 Update nightly-build workflow
  .github/workflows/nightly-build.yaml
Labels: approved, lgtm, size/M, kind/chore, release-note-none

#795 Remove unused code lines
  go.mod
  go.sum
  pkg/client/devops/fake/fakedevops.go
  pkg/client/devops/fake/fakedevops_test.go
  pkg/client/devops/jclient/credential.go
  pkg/client/devops/jclient/credential_test.go
  pkg/client/devops/jclient/pipeline.go
  pkg/client/devops/jenkins/build.go
  pkg/client/devops/jenkins/credential.go
  pkg/client/devops/jenkins/credential_test.go
  pkg/client/devops/jenkins/jenkins.go
  pkg/client/devops/jenkins/job.go
  pkg/client/devops/jenkins/pipeline.go
  pkg/client/devops/jenkins/pipeline_model_converter.go
  pkg/client/devops/pipeline.go
  pkg/client/devops/role.go
  pkg/client/devops/util/credential.go
  pkg/kapis/devops/v1alpha2/devops.go
  pkg/kapis/devops/v1alpha2/register.go
  pkg/models/devops/common.go
  pkg/models/devops/devops.go
Labels: size/XXL, release-note-none

#743 Add FluxCD Application Management
  Makefile
  cmd/controller/app/controllers.go
  config/crd/bases/gitops.kubesphere.io_applications.yaml
  config/rbac/role.yaml
  config/samples/gitops/fluxcd-application-helmrelease.yaml
  config/samples/gitops/fluxcd-application-helmtemplate.yaml
  config/samples/gitops/fluxcd-application-kustomization.yaml
  controllers/fluxcd/application-controller.go
  controllers/fluxcd/application-controller_test.go
  controllers/fluxcd/constants.go
  pkg/api/gitops/v1alpha1/application.go
  pkg/api/gitops/v1alpha1/constants.go
  pkg/api/gitops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apis.go
  pkg/external/fluxcd/helm/v2beta1/doc.go
  pkg/external/fluxcd/helm/v2beta1/groupversion_info.go
  pkg/external/fluxcd/helm/v2beta1/helmrelease_types.go
  pkg/external/fluxcd/helm/v2beta1/reference_types.go
  pkg/external/fluxcd/helm/v2beta1/zz_generated.deepcopy.go
  pkg/external/fluxcd/kustomize/v1beta2/doc.go
  pkg/external/fluxcd/kustomize/v1beta2/groupversion_info.go
  pkg/external/fluxcd/kustomize/v1beta2/kustomization_types.go
  pkg/external/fluxcd/kustomize/v1beta2/kustomize_types.go
  pkg/external/fluxcd/kustomize/v1beta2/reference_types.go
  pkg/external/fluxcd/kustomize/v1beta2/zz_generated.deepcopy.go
  pkg/external/fluxcd/meta/annotations.go
  pkg/external/fluxcd/meta/doc.go
  pkg/external/fluxcd/meta/reference_types.go
  pkg/external/fluxcd/meta/zz_generated.deepcopy.go
  pkg/external/fluxcd/source/v1beta2/artifact_types.go
  pkg/external/fluxcd/source/v1beta2/doc.go
  pkg/external/fluxcd/source/v1beta2/groupversion_info.go
  pkg/external/fluxcd/source/v1beta2/helmchart_types.go
  pkg/external/fluxcd/source/v1beta2/zz_generated.deepcopy.go
Labels: kind/feature, lgtm, size/XXL, kind/design, release-note-none

#799 Make gitops app kind to be optional
  config/crd/bases/gitops.kubesphere.io_applications.yaml
  pkg/api/gitops/v1alpha1/application.go
Labels: size/XS, kind/bug, release-note-none

#797 Support to add a Pipeline status link to git provider (github, gitlab, bitbucket)
  cmd/controller/app/controllers.go
  cmd/controller/app/options/feature.go
  cmd/controller/app/options/feature_test.go
  cmd/controller/app/options/options.go
  cmd/controller/app/options/options_test.go
  controllers/gitrepository/interface_test.go
  controllers/gitrepository/pull_request_status_controller.go
  controllers/gitrepository/pull_request_status_controller_test.go
  controllers/gitrepository/testdata/pr.json
  controllers/gitrepository/testdata/status.json
  pkg/api/devops/v1alpha3/pipelinerun_types.go
  pkg/client/git/client_test.go
  pkg/utils/net/net.go
  pkg/utils/net/net_test.go
Labels: kind/feature, size/XXL, release-note

#769 Add Multi-Cluster Management for Flux Application
  cmd/controller/app/controllers.go
  config/samples/gitops/fluxcd-application-helmrelease.yaml
  config/samples/gitops/fluxcd-application-helmtemplate.yaml
  config/samples/gitops/fluxcd-application-kustomization.yaml
  controllers/fluxcd/constants.go
  controllers/fluxcd/multi-cluster-controller.go
  controllers/fluxcd/multi-cluster-controller_test.go
Labels: kind/feature, size/XL, release-note-none

#801 Disable lint rule package-comments
  .golangci.yml
Labels: size/XS, kind/chore, release-note-none

#803 Support to set the cluster name
  cmd/controller/app/controllers.go
  cmd/controller/app/options/feature.go
  cmd/controller/app/options/feature_test.go
  controllers/gitrepository/pull_request_status_controller.go
Labels: kind/feature, size/S, release-note-none

#805 Doc: allow authenticated users checking Pipeline running log
  .golangci.yml
  docs/permission.md
Labels: size/S, kind/documentation, release-note-none
