Repository kubesphere/ks-devops, pull requests merged in 2022-03, with the labels that each got.

#484 Remove resource config due to non-existing fake CRD
  config/crd/kustomization.yaml
Labels: approved, lgtm, size/XS, kind/bug, release-note-none

#482 Add a flag to support skip Jenkins connection in the controller cmd
  cmd/controller/app/server.go
  pkg/client/devops/jclient/jenkins.go
  pkg/client/devops/jenkins/options.go
Labels: kind/feature, approved, lgtm, size/S, tide/merge-method-squash, release-note-none

#486 Fix the missing scheme register for the application
  pkg/apis/apis.go
Labels: approved, lgtm, size/XS, kind/bug, tide/merge-method-squash, release-note-none

#487 Add missing git secret support which belong to ks type
  config/samples/devops_v1alpha1_application.yaml
  pkg/client/git/client.go
  pkg/client/git/client_test.go
Labels: approved, lgtm, size/M, kind/bug, tide/merge-method-squash, release-note-none

#483 Support rendering Template with parameters
  config/samples/devops_v1alpha1_clustertemplate.yaml
  pkg/kapis/devops/v1alpha3/template/cluster_template_handler.go
  pkg/kapis/devops/v1alpha3/template/cluster_template_handler_test.go
  pkg/kapis/devops/v1alpha3/template/render.go
  pkg/kapis/devops/v1alpha3/template/render_test.go
  pkg/kapis/devops/v1alpha3/template/route.go
  pkg/kapis/devops/v1alpha3/template/route_test.go
  pkg/kapis/devops/v1alpha3/template/template_handler.go
  pkg/kapis/devops/v1alpha3/template/template_handler_test.go
Labels: kind/feature, size/L, approved, lgtm, tide/merge-method-squash, kind/api-change, release-note-none

#490 Fix the multi-branch pipeline creating
  pkg/client/devops/jclient/projectPipeline.go
  pkg/client/devops/jenkins/pipeline_internal.go
Labels: approved, lgtm, size/XS, kind/bug, tide/merge-method-squash, release-note-none

#489 Add required field into template parameter
  config/crd/bases/devops.kubesphere.io_clustertemplates.yaml
  config/crd/bases/devops.kubesphere.io_templates.yaml
  pkg/api/devops/v1alpha1/zz_generated.deepcopy.go
  pkg/api/devops/v1alpha3/template_types.go
Labels: kind/feature, approved, lgtm, size/S, tide/merge-method-squash, release-note-none

#492 Refine error tips when rendering template
  pkg/kapis/devops/v1alpha3/template/render.go
Labels: kind/feature, approved, lgtm, size/S, tide/merge-method-squash, release-note-none

#494 Redefine template delimiters to "$( )"
  config/samples/devops_v1alpha1_clustertemplate.yaml
  pkg/kapis/devops/v1alpha3/template/render.go
  pkg/kapis/devops/v1alpha3/template/render_test.go
Labels: kind/feature, approved, lgtm, size/M, tide/merge-method-squash, release-note-none

#495 Provider the APIs for the GitRepository custom resource
  Makefile
  config/crd/bases/devops.kubesphere.io_addons.yaml
  config/crd/bases/devops.kubesphere.io_addonstrategies.yaml
  config/crd/bases/devops.kubesphere.io_gitrepositories.yaml
  config/crd/bases/devops.kubesphere.io_webhooks.yaml
  config/samples/gitrepository.yaml
  controllers/addon/addon_controller.go
  controllers/addon/addon_controller_test.go
  controllers/addon/operator_controller.go
  controllers/addon/operator_controller_test.go
  controllers/gitrepository/gitrepository_webhook_controller.go
  controllers/gitrepository/gitrepository_webhook_controller_test.go
  controllers/gitrepository/webhook_notify.go
  controllers/gitrepository/webhook_notify_test.go
  pkg/api/devops/v1alpha1/zz_generated.deepcopy.go
  pkg/api/devops/v1alpha3/addon.go
  pkg/api/devops/v1alpha3/addon_strategy.go
  pkg/api/devops/v1alpha3/addon_strategy_test.go
  pkg/api/devops/v1alpha3/gitrepository.go
  pkg/api/devops/v1alpha3/webhook.go
  pkg/api/devops/v1alpha3/zz_generated.deepcopy.go
  pkg/client/git/client_test.go
  pkg/client/listers/devops/v1alpha1/gitrepository.go
  pkg/client/listers/devops/v1alpha1/webhook.go
  pkg/kapis/devops/v1alpha3/scm/gitrepository_handler.go
  pkg/kapis/devops/v1alpha3/scm/gitrepository_handler_test.go
  pkg/kapis/devops/v1alpha3/scm/route.go
  pkg/kapis/devops/v1alpha3/scm/scmhandler.go
Labels: kind/feature, approved, lgtm, size/XXL, tide/merge-method-squash, release-note-none

#497 Put the argocd application status to ks application
  cmd/controller/app/controllers.go
  config/crd/bases/gitops.kubesphere.io_applications.yaml
  config/rbac/role.yaml
  controllers/argocd/application_controller_test.go
  controllers/argocd/argocd-application-status-controller.go
  controllers/argocd/argocd-application-status-controller_test.go
  controllers/argocd/interface_test.go
  controllers/argocd/multi-cluster-controller_test.go
  controllers/argocd/project_controller_test.go
  pkg/api/gitops/v1alpha1/application.go
  pkg/api/gitops/v1alpha1/zz_generated.deepcopy.go
Labels: kind/feature, size/L, approved, lgtm, tide/merge-method-squash, release-note-none

#498 Fix the problem that PipelineRun is always in "Not Running" state
  controllers/jenkins/pipelinerun/utils.go
  controllers/jenkins/pipelinerun/utils_test.go
Labels: approved, lgtm, size/XS, kind/bug, tide/merge-method-squash, release-note

#499 Replace it with the new Jenkins client
  cmd/apiserver/app/options/options.go
  pkg/client/devops/jclient/jenkins.go
  pkg/client/devops/jenkins/devops.go
Labels: approved, lgtm, size/XS, tide/merge-method-squash, kind/flake, release-note-none

#500 Add a flag to ignore the connection faliure of Jenkins
  cmd/apiserver/app/options/options.go
Labels: kind/feature, approved, lgtm, size/XS, tide/merge-method-squash, release-note-none

#479 Create a new API to download artifacts from a PipelineRun
  go.mod
  go.sum
  pkg/client/devops/fake/fakedevops.go
  pkg/client/devops/jclient/pipeline.go
  pkg/client/devops/pipeline.go
  pkg/kapis/devops/v1alpha2/devops.go
  pkg/kapis/devops/v1alpha2/register.go
  pkg/kapis/devops/v1alpha2/register_test.go
  pkg/kapis/devops/v1alpha3/pipelinerun/handler.go
  pkg/kapis/devops/v1alpha3/pipelinerun/register.go
  pkg/kapis/devops/v1alpha3/pipelinerun/register_test.go
  pkg/kapis/devops/v1alpha3/register.go
Labels: kind/feature, size/L, approved, lgtm, tide/merge-method-squash, release-note-none

#442 Add a webhook to process pipeline event
  pkg/api/devops/v1alpha3/groupversion_info.go
  pkg/api/devops/v1alpha3/pipelinerun_types.go
  pkg/api/devops/v1alpha3/pipelinerun_types_test.go
  pkg/apiserver/apiserver.go
  pkg/event/README.md
  pkg/event/common/types.go
  pkg/event/workflowrun/actions.go
  pkg/event/workflowrun/actions_test.go
  pkg/event/workflowrun/parameter_action.go
  pkg/event/workflowrun/parameter_action_test.go
  pkg/event/workflowrun/types.go
  pkg/event/workflowrun/workflowrun_handler.go
  pkg/event/workflowrun/workflowrun_handler_test.go
  pkg/indexers/indexers.go
  pkg/kapis/devops/v1alpha3/handler.go
  pkg/kapis/devops/v1alpha3/pipelinerun/handler.go
  pkg/kapis/devops/v1alpha3/pipelinerun/register_test.go
  pkg/kapis/devops/v1alpha3/pipelinerun/util.go
  pkg/kapis/devops/v1alpha3/register.go
  pkg/kapis/devops/v1alpha3/webhook/handler.go
  pkg/kapis/devops/v1alpha3/webhook/register.go
  pkg/kapis/devops/v1alpha3/webhook/register_test.go
  pkg/kapis/devops/v1alpha3/webhook/workflowrun_handler.go
  pkg/kapis/devops/v1alpha3/webhook/workflowrun_handler_test.go
  pkg/kapis/utils.go
Labels: kind/feature, size/XXL, tide/merge-method-squash, release-note

#502 Add operation data into Argo Application
  config/crd/bases/gitops.kubesphere.io_applications.yaml
  config/samples/devops_v1alpha1_application.yaml
  config/samples/gitops_v1alpha1_application.yaml
  controllers/argocd/application_controller.go
  controllers/argocd/application_controller_test.go
  controllers/argocd/utils.go
  controllers/argocd/utils_test.go
  pkg/api/gitops/v1alpha1/application.go
  pkg/api/gitops/v1alpha1/zz_generated.deepcopy.go
  pkg/kapis/gitops/v1alpha1/argocd/route_test.go
Labels: kind/feature, approved, lgtm, size/XXL, tide/merge-method-squash, kind/cleanup, release-note-none

#503 Fix the incorrect version of the addon
  config/samples/addon/argocd.yaml
  config/samples/addon/argocd_simple_operator.yaml
  config/samples/addon/ks_releaser.yaml
  config/samples/addon/ks_releaser_simple_operator.yaml
  docs/addon.md
Labels: approved, lgtm, size/S, kind/documentation, tide/merge-method-squash, release-note-none

#491 Remove s2i reconciler from ks-devops
  cmd/controller/app/controllers.go
  cmd/controller/app/options/feature.go
  cmd/controller/app/options/feature_test.go
  controllers/s2ibinary/s2ibinary_controller.go
  controllers/s2ibinary/s2ibinary_controller_test.go
  controllers/s2irun/s2irun_controller.go
  controllers/s2irun/s2irun_controller_test.go
Labels: approved, lgtm, size/XXL, tide/merge-method-squash, kind/cleanup, release-note-none

#504 Avoid getting the Jenkins crumb when creating Jenkins client
  Makefile
  pkg/client/devops/jclient/jenkins.go
Labels: approved, lgtm, size/S, kind/bug, release-note-none

#506 Provide the ability to filter and sort for applications
  config/crd/bases/gitops.kubesphere.io_applications.yaml
  config/crd/kustomization.yaml
  controllers/argocd/argocd-application-status-controller.go
  pkg/api/gitops/v1alpha1/constants.go
  pkg/api/gitops/v1alpha1/groupversion_info.go
  pkg/apiserver/query/types.go
  pkg/kapis/common/options.go
  pkg/kapis/gitops/v1alpha1/argocd/handler.go
  pkg/kapis/gitops/v1alpha1/argocd/handler_test.go
  pkg/kapis/gitops/v1alpha1/argocd/route.go
  pkg/kapis/gitops/v1alpha1/argocd/route_test.go
  pkg/kapis/gitops/v1alpha1/argocd/util.go
  pkg/kapis/gitops/v1alpha1/argocd/util_test.go
Labels: kind/feature, size/L, approved, lgtm, tide/merge-method-squash, release-note-none

#505 Add missing RBAC permission claim
  config/rbac/role.yaml
  controllers/addon/addon_controller.go
  controllers/argocd/application_controller.go
  controllers/argocd/argocd-application-status-controller.go
  controllers/jenkins/config/jenkinsconfig_controller.go
  controllers/jenkins/devopscredential/devopscredential_controller.go
  controllers/jenkins/devopsproject/devopsproject_controller.go
  controllers/jenkins/pipeline/pipeline_metadata_controller.go
  pkg/kapis/devops/v1alpha2/register.go
  pkg/kapis/gitops/v1alpha1/registery.go
Labels: size/L, approved, lgtm, kind/chore, release-note-none

#516 Add missing rabc of the devopsproject
  config/rbac/role.yaml
  pkg/kapis/devops/v1alpha3/register.go
Labels: approved, lgtm, size/XS, release-note-none

#518 Fix an issue where the application status subresource was not updated
  controllers/argocd/application_controller.go
  controllers/argocd/argocd-application-status-controller.go
  controllers/argocd/argocd-application-status-controller_test.go
Labels: approved, size/M

#517 Provide applications summary API
  pkg/kapis/gitops/v1alpha1/argocd/handler.go
  pkg/kapis/gitops/v1alpha1/argocd/route.go
  pkg/kapis/gitops/v1alpha1/argocd/route_test.go
Labels: kind/feature, lgtm, size/M, release-note-none

#519 Provide a flag to set the namespace of the ArgoCD instance
  cmd/apiserver/app/options/options.go
  cmd/apiserver/app/server.go
  config/rbac/role.yaml
  controllers/argocd/application_controller.go
  controllers/argocd/application_controller_test.go
  controllers/argocd/argocd-application-status-controller.go
  controllers/argocd/argocd-application-status-controller_test.go
  pkg/api/gitops/v1alpha1/constants.go
  pkg/apiserver/apiserver.go
  pkg/config/argocd.go
  pkg/config/config.go
  pkg/kapis/gitops/v1alpha1/argocd/handler.go
  pkg/kapis/gitops/v1alpha1/argocd/route.go
  pkg/kapis/gitops/v1alpha1/argocd/route_test.go
  pkg/kapis/gitops/v1alpha1/registery.go
  pkg/utils/k8sutil/objectmeta.go
  pkg/utils/k8sutil/objectmeta_test.go
Labels: size/L, approved, lgtm, release-note-none

#520 Support to fetch repositories from a user account
  config/samples/secret.yaml
  controllers/gitrepository/gitrepository_webhook_controller.go
  controllers/gitrepository/gitrepository_webhook_controller_test.go
  go.mod
  go.sum
  pkg/client/git/client.go
  pkg/client/git/client_test.go
  pkg/kapis/common/options.go
  pkg/kapis/common/options_test.go
  pkg/kapis/devops/v1alpha3/scm/route.go
  pkg/kapis/devops/v1alpha3/scm/scmhandler.go
  pkg/kapis/devops/v1alpha3/scm/scmhandler_test.go
  pkg/kapis/devops/v1alpha3/scm/testdata/user.json
  pkg/kapis/devops/v1alpha3/scm/types.go
Labels: kind/feature, size/L, approved, release-note-none

#525 Fix the potential application update conflicts
  pkg/kapis/gitops/v1alpha1/argocd/handler.go
Labels: approved, size/S, kind/bug, release-note-none

#526 Support list the git repository list with paging
  pkg/apiserver/query/types.go
  pkg/kapis/common/options.go
  pkg/kapis/devops/v1alpha3/scm/gitrepository_handler.go
  pkg/kapis/devops/v1alpha3/scm/route.go
  pkg/kapis/devops/v1alpha3/scm/types.go
  pkg/kapis/gitops/v1alpha1/argocd/route.go
Labels: approved, size/M, release-note-none
