Repository kubesphere/ks-devops, pull requests merged in 2022-01, with the labels that each got.

#326 Avoid returning secret value of the DevOps credential by creating credential mask
  pkg/api/devops/v1alpha3/credential_types.go
  pkg/api/devops/v1alpha3/credential_types_test.go
  pkg/models/devops/devops.go
  pkg/utils/secretutil/secret_mask.go
  pkg/utils/secretutil/secret_mask_test.go
Labels: size/L, approved, lgtm, kind/bug, tide/merge-method-squash, release-note-none

#434 Add unit tests for the APIs
  .golangci.yml
  pkg/api/devops/v1alpha1/zz_generated.deepcopy.go
  pkg/api/devops/v1alpha3/zz_generated.deepcopy.go
  pkg/apiserver/apiserver.go
  pkg/client/k8s/fake_client.go
  pkg/constants/constants.go
  pkg/kapis/devops/v1alpha2/register_test.go
  pkg/kapis/devops/v1alpha3/handler.go
  pkg/kapis/devops/v1alpha3/pipeline/register_test.go
  pkg/kapis/devops/v1alpha3/pipelinerun/register_test.go
  pkg/kapis/devops/v1alpha3/register_test.go
  pkg/kapis/oauth/handler.go
  pkg/kapis/oauth/register.go
  pkg/kapis/oauth/register_test.go
Labels: approved, lgtm, size/XL, tide/merge-method-squash, kind/chore, release-note-none

#436 Add test cases for the api package
  pkg/api/devops/v1alpha1/openapi_generated_test.go
  pkg/api/devops/v1alpha1/register_test.go
  pkg/api/devops/v1alpha2/types.go
  pkg/api/devops/v1alpha3/groupversion_info_test.go
  pkg/api/devops/v1alpha3/pipelinerun_types_test.go
  pkg/client/k8s/kubernetes.go
  pkg/models/devops/project.go
Labels: size/L, approved, lgtm, tide/merge-method-squash, release-note-none, kind/test

#437 Using the new Jenkins client library
  .github/workflows/build.yaml
  cmd/controller/app/server.go
  controllers/pipeline/pipeline_controller.go
  controllers/pipeline/pipeline_controller_test.go
  go.mod
  go.sum
  pkg/api/devops/v1alpha1/zz_generated.deepcopy.go
  pkg/api/devops/v1alpha3/zz_generated.deepcopy.go
  pkg/client/devops/fake/fakeJenkinsClient.go
  pkg/client/devops/fake/fakedevops.go
  pkg/client/devops/interface.go
  pkg/client/devops/interface_test.go
  pkg/client/devops/jclient/build.go
  pkg/client/devops/jclient/configuration.go
  pkg/client/devops/jclient/credential.go
  pkg/client/devops/jclient/jenkins.go
  pkg/client/devops/jclient/pipeline.go
  pkg/client/devops/jclient/project.go
  pkg/client/devops/jclient/projectPipeline.go
  pkg/client/devops/jenkins/jenkins.go
  pkg/client/devops/jenkins/pipeline.go
  pkg/client/devops/jenkins/project.go
  pkg/client/devops/jenkins/role.go
  pkg/client/devops/pipeline.go
  pkg/client/devops/role.go
  pkg/kapis/devops/v1alpha2/devops.go
  pkg/kapis/devops/v1alpha2/register.go
  pkg/models/devops/devops.go
Labels: approved, lgtm, size/XXL, tide/merge-method-squash, kind/chore, release-note-none

#438 Add Swagger service support
  Makefile
  config/dockerfiles/apiserver/Dockerfile
  controllers/gitrepository/gitrepository_webhook_controller.go
  docs/README.md
  docs/swagger.md
  go.mod
  go.sum
  pkg/api/devops/v1alpha1/zz_generated.deepcopy.go
  pkg/api/devops/v1alpha3/zz_generated.deepcopy.go
  pkg/apiserver/apiserver.go
  pkg/kapis/devops/v1alpha2/register.go
  pkg/kapis/devops/v1alpha2/register_test.go
  pkg/kapis/devops/v1alpha3/register.go
  pkg/kapis/doc/register_test.go
  pkg/kapis/doc/registry.go
  pkg/kapis/oauth/register.go
Labels: size/L, approved, lgtm, tide/merge-method-squash, kind/chore, release-note

#435 Fix the API for getting devops project
  pkg/apiserver/filters/requestinfo.go
  pkg/kapis/devops/v1alpha3/handler.go
  pkg/kapis/devops/v1alpha3/register.go
  pkg/kapis/devops/v1alpha3/register_test.go
  pkg/models/devops/devops.go
  pkg/models/devops/devops_test.go
Labels: size/L, approved, kind/bug, release-note

#441 fix: Using defer in loops and end of loop call fileData.Close() can lead to resource leaks
  pkg/client/devops/jenkins/request.go
  pkg/client/devops/jenkins/request_test.go
  pkg/client/devops/jenkins/utils.go
  pkg/client/devops/jenkins/utils_test.go
Labels: size/L, kind/bug, tide/merge-method-squash, release-note-none

#428 Delete PipelineRun not found in Jenkins
  controllers/jenkins/pipelinerun/pipelinerun_controller.go
  controllers/jenkins/pipelinerun/pipelinerun_synchronizer.go
  controllers/jenkins/pipelinerun/pipelinerun_synchronizer_test.go
  pkg/api/devops/v1alpha3/pipeline_types.go
  pkg/api/devops/v1alpha3/pipeline_types_test.go
Labels: size/L, approved, lgtm, kind/bug, tide/merge-method-squash, release-note-none

#439 Support to verify SCM token directly instead of call Jenkins API
  cmd/apiserver/app/options/options.go
  controllers/gitrepository/gitrepository_webhook_controller.go
  go.mod
  go.sum
  pkg/apiserver/filters/requestinfo.go
  pkg/client/devops/jenkins/pure_request.go
  pkg/client/git/client.go
  pkg/client/git/client_test.go
  pkg/client/git/message.go
  pkg/client/git/message_test.go
  pkg/kapis/devops/v1alpha3/handler.go
  pkg/kapis/devops/v1alpha3/register.go
  pkg/kapis/devops/v1alpha3/register_test.go
  pkg/kapis/devops/v1alpha3/scm/scmhandler.go
  pkg/kapis/devops/v1alpha3/scm/scmhandler_test.go
  pkg/kapis/devops/v1alpha3/testdata/orgs.json
Labels: kind/feature, approved, lgtm, size/XL, tide/merge-method-squash, release-note

#455 Fix error handle jclient.NewJenkinsClient()
  pkg/client/devops/jclient/jenkins.go
Labels: approved, lgtm, size/S, kind/bug, release-note-none

#456 Add two issue templates, bug report and feature request
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: approved, lgtm, size/M, kind/documentation, release-note-none
