Repository kubesphere/ks-devops, pull requests merged in 2023-01, with the labels that each got.

#838 Improve the notification of build result to git provider
  controllers/gitrepository/pull_request_status_controller.go
  controllers/gitrepository/pull_request_status_controller_test.go
Labels: kind/feature, approved, lgtm, size/M, release-note-none

#874 bugfix: nil pointer of CompletionTime
  controllers/gitrepository/pull_request_status_controller.go
Labels: approved, lgtm, size/XS, kind/bug, release-note-none

#855 Support to store PipelineRun data into ConfigMap (#825)
  Makefile
  cmd/controller/app/controllers.go
  cmd/controller/app/options/feature.go
  cmd/controller/app/options/feature_test.go
  controllers/jenkins/pipelinerun/pipelinerun_controller.go
  controllers/jenkins/pipelinerun/pipelinerun_controller_test.go
  pkg/kapis/devops/v1alpha3/pipelinerun/handler.go
  pkg/kapis/devops/v1alpha3/pipelinerun/handler_test.go
  pkg/store/configmap/pipelinerun.go
  pkg/store/configmap/pipelinerun_test.go
  pkg/store/fake/fake_core_test.go
  pkg/store/fake/fake_store.go
  pkg/store/store/types.go
  pkg/store/store/types_test.go
Labels: approved, lgtm, size/XL, release-note

#875 Assign pipelinerun data store to reconsiler
  cmd/controller/app/controllers.go
  controllers/jenkins/pipelinerun/pipelinerun_controller.go
Labels: approved, lgtm, size/S, release-note

#879 add latest build action
  .github/workflows/latest-build.yaml
Labels: size/L, approved, lgtm, kind/cleanup

#880 change user for ghcr to kubesphere
  .github/workflows/latest-build.yaml
Labels: size/XS, release-note-none

#881 Fix test & Fix action
  .github/workflows/latest-build.yaml
  controllers/jenkins/pipelinerun/pipelinerun_controller_test.go
Labels: size/M, release-note-none

#883 change latest-build github action, use github.ref_name tag
  .github/workflows/latest-build.yaml
Labels: size/M, release-note-none

#882 add latest build action, same as: #879
  .github/workflows/latest-build.yaml
Labels: size/L, release-note-none

#884 fix latest-build action skopeo cmd
  .github/workflows/latest-build.yaml
Labels: size/XS, release-note-none

#885 update: save pipelinerun result to annotation
  controllers/jenkins/pipelinerun/pipelinerun_controller.go
Labels: bug, approved, lgtm, size/S

#887 update: save pipelinerun result to annotation (#885)
  controllers/jenkins/pipelinerun/pipelinerun_controller.go
Labels: approved, lgtm, size/S, kind/bug, release-note

#886 Bugfix ks 5193
  pkg/client/devops/jclient/projectPipeline.go
  pkg/client/devops/jenkins/constants.go
  pkg/client/devops/jenkins/pipeline_internal.go
  pkg/client/devops/jenkins/project_pipeline.go
  pkg/client/devops/jenkins/triggers/genericwebhook.go
Labels: size/L, approved, lgtm, kind/bug, release-note

#888 bugfix ks 5193
  pkg/client/devops/jclient/projectPipeline.go
  pkg/client/devops/jenkins/constants.go
  pkg/client/devops/jenkins/pipeline_internal.go
  pkg/client/devops/jenkins/project_pipeline.go
  pkg/client/devops/jenkins/triggers/genericwebhook.go
Labels: size/L, approved, lgtm, kind/bug, release-note

#889 update test func: storePipelineRunData
  controllers/jenkins/pipelinerun/pipelinerun_controller_test.go
  pkg/client/devops/jenkins/triggers/genericwebhook.go
Labels: approved, lgtm, size/XS, kind/failing-test, release-note-none

#891 add check: lint and unit-test for PR
  .github/workflows/check.yaml
Labels: approved, lgtm, size/S, kind/chore, release-note-none
