Repository kubesphere/ks-devops, pull requests merged in 2023-02, with the labels that each got.

#894 update reviewer
  OWNERS
Labels: approved, lgtm, size/XS, kind/chore, release-note-none

#893 bugfix: the status of pipelinerun change to not running after cancel it
  config/crd/bases/devops.kubesphere.io_pipelineruns.yaml
  controllers/jenkins/pipelinerun/pipelinerun_controller.go
  pkg/api/devops/v1alpha3/pipelinerun_types.go
Labels: approved, lgtm, size/S, kind/bug, release-note

#897 format code with lint
  controllers/jenkins/pipelinerun/pipelinerun_controller.go
Labels: approved, lgtm, size/S, kind/flake, release-note-none

#902 Auto sync jenkinsfile for pre version pipeline
  controllers/jenkins/pipeline/json_converter.go
  controllers/jenkins/pipeline/json_converter_test.go
  controllers/jenkins/pipeline/pipeline_controller.go
  controllers/jenkins/pipeline/pipeline_metadata_controller.go
  controllers/jenkins/pipelinerun/pipelinerun_controller.go
  pkg/api/devops/v1alpha3/pipeline_types.go
Labels: size/L, approved, lgtm, kind/bug, release-note

#906 add retry for pipelinerun annotation update
  controllers/jenkins/pipelinerun/pipelinerun_controller.go
Labels: approved, lgtm, size/S, release-note

#909 Fix reconcile json edit mode
  config/rbac/role.yaml
  controllers/jenkins/pipeline/json_converter.go
Labels: approved, lgtm, size/M, release-note-none
