Repository kubesphere/ks-devops, pull requests merged in 2023-10, with the labels that each got.

#1001 Fix shell validate failed
  controllers/jenkins/pipeline/json_converter.go
  pkg/api/devops/v1alpha3/steptemplate_render.go
  pkg/api/devops/v1alpha3/steptemplate_render_test.go
Labels: approved, lgtm, size/S, release-note

#1004 add header info in api run-log
  pkg/client/devops/fake/fakedevops.go
  pkg/client/devops/fake/fakedevops_test.go
  pkg/client/devops/jclient/pipeline.go
  pkg/client/devops/jenkins/jenkins.go
  pkg/client/devops/jenkins/pipeline.go
  pkg/client/devops/pipeline.go
  pkg/kapis/devops/v1alpha2/devops.go
  pkg/models/devops/devops.go
Labels: approved, lgtm, size/M, kind/bug, release-note-none

#1009 update swagger info for SwaggerUI
  cmd/apiserver/app/options/options.go
  cmd/controller/app/options/options.go
  docs/swagger.md
  pkg/config/gitops.go
  pkg/kapis/doc/registry.go
Labels: approved, lgtm, size/M, release-note-none

#1015 fix panic when timeout is nil in gitlab cloneOptions
  pkg/client/devops/jenkins/internal/gitlab.go
Labels: approved, lgtm, size/S, kind/bug, release-note

#999 Imagebuild
  go.mod
  go.sum
  pkg/apis/addtoscheme_imagebuilder_v1alpha1.go
  pkg/apiserver/apiserver.go
  pkg/constants/constants.go
  pkg/kapis/imagebuilder/v1alpha1/handler.go
  pkg/kapis/imagebuilder/v1alpha1/handler_test.go
  pkg/kapis/imagebuilder/v1alpha1/register.go
  pkg/kapis/imagebuilder/v1alpha1/register_test.go
Labels: approved, lgtm, size/XXL, kind/failing-test, kind/design, kind/api-change, release-note-none
