Repository kubesphere/ks-devops, pull requests merged in 2025-04, with the labels that each got.

#1052 remove devops namespace ownerreferences
  controllers/jenkins/devopscredential/devopscredential_controller.go
  controllers/jenkins/devopsproject/devopsproject_controller.go
Labels: lgtm, size/S, release-note

#1053 update agent info to annotation
  cmd/controller/app/controllers.go
  controllers/jenkins/pipelinerun/pipelinerun_controller.go
  pkg/api/devops/v1alpha3/groupversion_info.go
Labels: approved, size/M

#1051 add git repository reachability validation
  .gitignore
  pkg/client/git/client.go
  pkg/kapis/devops/v1alpha3/scm/gitrepository_handler.go
  pkg/kapis/devops/v1alpha3/scm/scmhandler.go
  pkg/kapis/devops/v1alpha3/scm/utils.go
Labels: kind/feature, size/L, approved, lgtm, release-note

#1054 fix argocd controller
  controllers/argocd/multi-cluster-controller.go
  controllers/argocd/multi-cluster-controller_test.go
  controllers/fluxcd/multi-cluster-controller.go
  controllers/fluxcd/multi-cluster-controller_test.go
Labels: size/L, release-note

#1055 update dependency
  go.mod
  go.sum
Labels: size/S, release-note

#1056 fix: pod name couldn't be empty
  controllers/jenkins/pipelinerun/pipelinerun_controller.go
Labels: approved, lgtm, size/XS, kind/bug, release-note-none
